<!DOCTYPE html>
<html lang="en"><head>
<script src="lec-12-power_MH_files/libs/clipboard/clipboard.min.js"></script>
<script src="lec-12-power_MH_files/libs/quarto-html/tabby.min.js"></script>
<script src="lec-12-power_MH_files/libs/quarto-html/popper.min.js"></script>
<script src="lec-12-power_MH_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="lec-12-power_MH_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="lec-12-power_MH_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="lec-12-power_MH_files/libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.38">

  <title>Lecture 12: Power, sample size, and correlation</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="lec-12-power_MH_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="lec-12-power_MH_files/libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="lec-12-power_MH_files/libs/revealjs/dist/theme/quarto-2740581606dc327e82f18f789b69d8a0.css">
  <link rel="stylesheet" href="reveal-custom.css">
  <link href="lec-12-power_MH_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="lec-12-power_MH_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="lec-12-power_MH_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="lec-12-power_MH_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Lecture 12: Power, sample size, and correlation</h1>
  <p class="subtitle">BIOS 600 - Summer Session II 2026</p>

<div class="quarto-title-authors">
</div>

</section>
<section id="announcements" class="slide level2">
<h2>Announcements</h2>
<ul>
<li><p>HW11 due <strong>tonight</strong> by 11:59 PM</p></li>
<li><p>HW12 due <strong>tomorrow</strong> by 11:59 PM</p></li>
<li><p>Exam 2 on Thursday! Tomorrow’s class will be for review</p></li>
</ul>
</section>
<section id="overview" class="slide level2">
<h2>Overview</h2>
<ul>
<li><p>Why calculate sample size and power?</p></li>
<li><p>How to calculate sample size and power in R</p></li>
<li><p>Comparing two continuous variables</p></li>
</ul>
</section>
<section id="very-optional-reading" class="slide level2">
<h2>Very optional reading</h2>
<ul>
<li><p>P&amp;G Sections 10.4 and 10.6, 17</p></li>
<li><p>OI: Section 8.1</p></li>
</ul>
</section>
<section id="t-tests-in-r" class="slide level2 smaller">
<h2>T-tests in R</h2>
<ul>
<li><p>The one-sample, two-sample, and paired t-tests all are run in R using the function <code>t.test()</code>, but with slightly different syntax for each.</p></li>
<li><p>For the one-sample t-test:</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href=""></a><span class="co"># one-sample t-test</span></span>
<span id="cb1-2"><a href=""></a></span>
<span id="cb1-3"><a href=""></a><span class="fu">t.test</span>(dataset<span class="sc">$</span>outcome,           <span class="co"># variable whose mean we are testing</span></span>
<span id="cb1-4"><a href=""></a>       <span class="at">mu =</span> <span class="dv">0</span>)                    <span class="co"># mean under the null (defaults to 0)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li><p>We can also specify the alternative hypothesis (the default is a two-sided test) and the confidence level (the default is 0.95).</p></li>
<li><p>We do not need to specify <code>paired</code> or <code>var.equal</code>, because we only have one sample.</p></li>
</ul>
</section>
<section id="t-tests-in-r-1" class="slide level2 smaller">
<h2>T-tests in R</h2>
<ul>
<li>For the two-sample t-test:</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href=""></a><span class="co"># two-sample t-test</span></span>
<span id="cb2-2"><a href=""></a></span>
<span id="cb2-3"><a href=""></a><span class="fu">t.test</span>(outcome <span class="sc">~</span> group,           <span class="co"># variable whose mean we are testing ~</span></span>
<span id="cb2-4"><a href=""></a>                                  <span class="co"># variable differentiating the two groups</span></span>
<span id="cb2-5"><a href=""></a>       <span class="at">data =</span> dataset,            <span class="co"># name of the dataset</span></span>
<span id="cb2-6"><a href=""></a>       <span class="at">mu =</span> <span class="dv">0</span>,                    <span class="co"># difference in means under the null (default 0)</span></span>
<span id="cb2-7"><a href=""></a>       <span class="at">var.equal =</span> <span class="cn">FALSE</span>)         <span class="co"># is the variance the same between two populations</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li><p>We can also specify the alternative hypothesis (the default is a two-sided test) and the confidence level (the default is 0.95).</p></li>
<li><p>The default for <code>var.equal</code> is false and we do not specify <code>paired</code>.</p></li>
</ul>
</section>
<section id="t-tests-in-r-2" class="slide level2 smaller">
<h2>T-tests in R</h2>
<ul>
<li>For the paired t-test:</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href=""></a><span class="co"># paired t-test</span></span>
<span id="cb3-2"><a href=""></a></span>
<span id="cb3-3"><a href=""></a><span class="fu">t.test</span>(dataset<span class="sc">$</span>baseline,          <span class="co"># variable with first part of paired data</span></span>
<span id="cb3-4"><a href=""></a>       dataset<span class="sc">$</span>final,             <span class="co"># variable with second part of paired data</span></span>
<span id="cb3-5"><a href=""></a>       <span class="at">data =</span> dataset,            <span class="co"># name of the dataset</span></span>
<span id="cb3-6"><a href=""></a>       <span class="at">mu =</span> <span class="dv">0</span>,                    <span class="co"># difference in means under the null (default 0)</span></span>
<span id="cb3-7"><a href=""></a>       <span class="at">paired =</span> <span class="cn">TRUE</span>)             <span class="co"># indicates a paired test</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li><p>We can also specify the alternative hypothesis (the default is a two-sided test) and the confidence level (the default is 0.95).</p></li>
<li><p>We do not need to specify <code>var.equal()</code>.</p></li>
<li><p>The two columns with the data can be in either order; if you flip them, the test statistic will change sign but have the same magnitude.</p></li>
</ul>
</section>
<section id="t-tests-in-r-3" class="slide level2 smaller">
<h2>T-tests in R</h2>
<ul>
<li>For the two-sample t-test:</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href=""></a><span class="co"># two-sample t-test</span></span>
<span id="cb4-2"><a href=""></a></span>
<span id="cb4-3"><a href=""></a><span class="fu">t.test</span>(outcome <span class="sc">~</span> group,           <span class="co"># variable whose mean we are testing ~</span></span>
<span id="cb4-4"><a href=""></a>                                  <span class="co"># variable differentiating the two groups</span></span>
<span id="cb4-5"><a href=""></a>       <span class="at">data =</span> dataset,            <span class="co"># name of the dataset</span></span>
<span id="cb4-6"><a href=""></a>       <span class="at">mu =</span> <span class="dv">0</span>,                    <span class="co"># difference in means under the null (default 0)</span></span>
<span id="cb4-7"><a href=""></a>       <span class="at">var.equal =</span> <span class="cn">FALSE</span>)         <span class="co"># is the variance the same between two populations</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li><p>We can also specify the alternative hypothesis (the default is a two-sided test) and the confidence level (the default is 0.95).</p></li>
<li><p>The default for <code>var.equal</code> is false and we do not specify <code>paired</code>.</p></li>
</ul>
</section>
<section id="t-tests-in-r-4" class="slide level2">
<h2>T-tests in R</h2>
<ul>
<li><p>For the one-sample t-test and the paired t-test, you have the option to specify <code>data = dataset</code> as input to the function.</p></li>
<li><p>If you do this, you shouldn’t include <code>data$</code> before the column names you are testing.</p></li>
<li><p>The last three slides are good examples of commenting your code; commenting makes it easier for you to understand your thought process while coding, and also will make it easier for anyone else reading your code to understand what it does.</p></li>
</ul>
</section>
<section id="mapping-parametric-to-nonparametric-tests" class="slide level2 smaller">
<h2>Mapping Parametric to Non‑Parametric Tests</h2>
<table class="caption-top">
<colgroup>
<col style="width: 38%">
<col style="width: 28%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Non‑Parametric Test</th>
<th>Parametric Test</th>
<th>Key Features</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Sign test</strong></td>
<td>Paired t‑test</td>
<td>Uses only <strong>direction</strong> (+/–) of paired differences; ignores magnitude; requires only independence</td>
</tr>
<tr class="even">
<td><strong>Wilcoxon signed‑rank</strong></td>
<td>Paired t‑test</td>
<td>Uses <strong>magnitude + direction</strong> of paired differences; requires <strong>symmetric distribution</strong> of differences</td>
</tr>
</tbody>
</table>
</section>
<section id="mapping-parametric-to-nonparametric-tests-1" class="slide level2 smaller">
<h2>Mapping Parametric to Non‑Parametric Tests</h2>
<table class="caption-top">
<colgroup>
<col style="width: 34%">
<col style="width: 36%">
<col style="width: 29%">
</colgroup>
<thead>
<tr class="header">
<th>Non‑Parametric</th>
<th>Parametric Test</th>
<th>Key Features</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Mann–Whitney U/</strong> <br> <strong>Wilcoxon rank‑sum</strong></td>
<td>Two‑sample t‑test</td>
<td>Rank‑based comparison of two independent groups</td>
</tr>
<tr class="even">
<td><strong>Kruskal–Wallis</strong></td>
<td>One‑way ANOVA</td>
<td>Rank‑based comparison of 3+ independent groups</td>
</tr>
</tbody>
</table>
</section>
<section id="non-parametric-alternative-for-one-sample-test" class="slide level2 smaller">
<h2>Non-parametric alternative for one-sample test</h2>
<ul>
<li><p>Much like how the paired t-test and one-sample t-test are equivalent in the parametric case, you can use the sign test or the Wilcoxon signed-rank test for a one-sample test of the median.</p></li>
<li><p>As an example, suppose we have a small sample of systolic blood pressures and want to test if the median blood pressure in this population is equal to 110 mmHg.</p></li>
</ul>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th>1</th>
<th>2</th>
<th>3</th>
<th>4</th>
<th>5</th>
<th>6</th>
<th>7</th>
<th>8</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Blood Pressure (mmHg)</td>
<td>97</td>
<td>113</td>
<td>100</td>
<td>128</td>
<td>96</td>
<td>105</td>
<td>86</td>
<td>110</td>
</tr>
</tbody>
</table>
<ul>
<li>Instead of taking a difference between before/after values, we would conduct the sign test by first subtracting 110 from each of these blood pressures.</li>
</ul>
</section>
<section id="non-parametric-alternative-for-one-sample-test-1" class="slide level2 smaller">
<h2>Non-parametric alternative for one-sample test</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th>1</th>
<th>2</th>
<th>3</th>
<th>4</th>
<th>5</th>
<th>6</th>
<th>7</th>
<th>8</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>BP - 110</td>
<td>-13</td>
<td>3</td>
<td>-10</td>
<td>18</td>
<td>-14</td>
<td>-5</td>
<td>-24</td>
<td>0</td>
</tr>
<tr class="even">
<td>Sign</td>
<td>-</td>
<td>+</td>
<td>-</td>
<td>+</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>0</td>
</tr>
</tbody>
</table>
<p>We have 7 non-zero differences, and 2 “successes”. From here, we follow the same procedure as with the paired case:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href=""></a>p_value <span class="ot">&lt;-</span> <span class="dv">2</span><span class="sc">*</span>(<span class="fu">pbinom</span>(<span class="dv">2</span>, <span class="dv">7</span>, <span class="fl">0.5</span>))</span>
<span id="cb5-2"><a href=""></a>p_value</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.453125</code></pre>
</div>
</div>
<p>With this p-value, we fail to reject the null hypothesis and do not have statistically significant evidence that the median blood pressure in this population is <strong>not equal</strong> to 110 mmHg.</p>
</section>
<section id="why-calculate-sample-size-and-power" class="slide level2">
<h2>Why calculate sample size and power?</h2>
<ul>
<li><p>To show that under certain required conditions, a hypothesis test has a <strong>good chance of showing the anticipated difference</strong>, if it really exists</p></li>
<li><p>To be more confident that a null result is not simply a sample of excessive variability</p></li>
<li><p>To show a funding agency that the study has a reasonable chance of reaching a useful result (leading them to <strong>fund your grant</strong>!)</p></li>
<li><p>To show that necessary resources (human, animal, financial, time, etc.) will be minimized</p></li>
</ul>
</section>
<section id="power" class="slide level2 smaller">
<h2>Power</h2>
<ul>
<li><p>Showing adequate statistical power is usually necessary in order to <strong>get funding for research</strong>!</p></li>
<li><p><strong>Power</strong> is the probability of rejecting the null hypothesis when it is false (i.e., of avoiding a Type II error)</p></li>
</ul>
<div class="poll">
<p><span class="math display">\[\text{Power} = P(\text{reject } H_0 | H_0 \text{ is false})\]</span></p>
</div>
<p>and can be also thought of as the likelihood a planned study will detect a deviation from the null hypothesis if one really exists. Power is a function of:</p>
<ul>
<li><p>Sample size <span class="math inline">\(n\)</span></p></li>
<li><p>Deviation from the null one hopes to detect</p></li>
<li><p>Standard deviation <span class="math inline">\(σ\)</span></p></li>
<li><p><span class="math inline">\(\alpha\)</span>, the Type I error rate</p></li>
</ul>
</section>
<section id="power-and-error-rates" class="slide level2">
<h2>Power and Error Rates</h2>
<ul>
<li>Recall: When we conduct a hypothesis test, there are <strong>four possible outcomes</strong> depending on the true state of the null hypothesis and the decision we make.</li>
</ul>
<table class="caption-top">
<colgroup>
<col style="width: 35%">
<col style="width: 31%">
<col style="width: 32%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Decision</strong></th>
<th><strong>Truth: (<span class="math inline">\(H_0\)</span>) True</strong></th>
<th><strong>Truth: (<span class="math inline">\(H_0\)</span>) False</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Reject (<span class="math inline">\(H_0\)</span>)</strong></td>
<td>Type I Error (<span class="math inline">\(\alpha\)</span>)</td>
<td>Correct Decision → Power (<span class="math inline">\(1−\beta\)</span>)</td>
</tr>
<tr class="even">
<td><strong>Fail to Reject (<span class="math inline">\(H_0\)</span>)</strong></td>
<td>Correct Decision</td>
<td>Type II Error (<span class="math inline">\(\beta\)</span>)</td>
</tr>
</tbody>
</table>
</section>
<section id="n-detectable-difference-variance-and-alpha" class="slide level2">
<h2>n, detectable difference, variance, and <span class="math inline">\(\alpha\)</span></h2>
<p>How do these four considerations affect power?</p>
<ul>
<li><p>When we design a study, it is not enough to know we have a small probability of rejecting <span class="math inline">\(H_0\)</span> when it is in fact true (i.e.&nbsp;setting <span class="math inline">\(\alpha = 0.05\)</span>).</p></li>
<li><p>We want to know we have a large probability of rejecting the null when it is false. Practically speaking, <strong>power less than 80% is typically considered insufficient to warrant a study</strong>.</p></li>
</ul>
</section>
<section id="power-1" class="slide level2">
<h2>Power</h2>
<ul>
<li><p>Recall: In our medical diagnostics lecture, we saw that there is a tradeoff between Type 1 and Type 2 error. Lowering <span class="math inline">\(\alpha\)</span> makes it harder to reject the null hypothesis, which usually reduces power—we’re less likely to catch real effects (true positives).</p></li>
<li><p>Increasing power by tolerating more Type I errors is <strong>not acceptable</strong>. Therefore, we can increase power by</p></li>
<li><p>Considering <strong>larger deviations from the null</strong> (need to think about clinical/practical importance)</p></li>
<li><p>Increasing <span class="math inline">\(n\)</span> (good, though not always affordable)</p></li>
</ul>
</section>
<section id="interactive-visualization" class="slide level2">
<h2>Interactive visualization</h2>
<p><a href="http://rpsychologist.com/d3/NHST/" class="uri">http://rpsychologist.com/d3/NHST/</a></p>
<p>Let’s check out this interactive visualization to see how this all works for a one-sample z-test.</p>
</section>
<section id="power-depends-on" class="slide level2 smaller">
<h2>Power Depends On…</h2>
<table class="caption-top">
<colgroup>
<col style="width: 16%">
<col style="width: 18%">
<col style="width: 28%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Factor</th>
<th style="text-align: center;">Change</th>
<th style="text-align: left;">Effect on Power</th>
<th style="text-align: left;">Intuition</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Sample size (<span class="math inline">\(n\)</span>)</td>
<td style="text-align: center;"><span class="math inline">\(\uparrow\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\uparrow\)</span> <strong>Increases</strong></td>
<td style="text-align: left;">More data → smaller SE → easier to detect true effects</td>
</tr>
<tr class="even">
<td style="text-align: left;">Variability (<span class="math inline">\(\sigma^2\)</span>)</td>
<td style="text-align: center;"><span class="math inline">\(\uparrow\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\downarrow\)</span> <strong>Decreases</strong></td>
<td style="text-align: left;">More noise → harder to detect signal</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Effect size (<span class="math inline">\(\delta\)</span>)</td>
<td style="text-align: center;"><span class="math inline">\(\uparrow\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\uparrow\)</span> <strong>Increases</strong></td>
<td style="text-align: left;">Larger true difference → easier to detect</td>
</tr>
<tr class="even">
<td style="text-align: left;">Significance level (<span class="math inline">\(\alpha\)</span>)</td>
<td style="text-align: center;"><span class="math inline">\(\uparrow\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\uparrow\)</span> <strong>Increases</strong></td>
<td style="text-align: left;">More lenient threshold → higher chance to reject <span class="math inline">\(H_0\)</span></td>
</tr>
</tbody>
</table>
</section>
<section id="understanding-power" class="slide level2">
<h2>Understanding power</h2>
<ul>
<li><p>Holding <span class="math inline">\(n\)</span>, variance, and <span class="math inline">\(\alpha\)</span> constant, we have <strong>more power</strong> to detect a <strong>larger difference</strong> compared to a smaller one.</p></li>
<li><p>Holding variance, effect size, and <span class="math inline">\(\alpha\)</span> constant, <strong>increasing sample size (<span class="math inline">\(n\)</span>)</strong> increases power — with more data, we’re more likely to detect true effects.</p></li>
</ul>
</section>
<section id="understanding-power---your-turn" class="slide level2">
<h2>Understanding Power - Your turn!</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Circle One</strong></p>
</div>
<div class="callout-content">
<ul>
<li><p>Holding <span class="math inline">\(n\)</span>, effect size, and <span class="math inline">\(\alpha\)</span> constant, <strong>(higher/lower)</strong> variance decreases power because the signal is harder to detect within the noise.</p></li>
<li><p>Holding <span class="math inline">\(n\)</span>, variance, and effect size constant, <strong>(increasing/decreasing)</strong> <span class="math inline">\(\alpha\)</span> increases power — we’re more willing to reject the null, so true effects are easier to detect.</p></li>
</ul>
</div>
</div>
</div>
</section>
<section id="what-is-this-deviation" class="slide level2 smaller">
<h2>What is this deviation?</h2>
<p>When we calculate power, we need to know the minimum difference from the null mean <span class="math inline">\(\mu_0\)</span> that we wish to detect. We may set up our hypotheses as</p>
<p><span class="math display">\[H_0: \mu = \mu_0\]</span></p>
<p><span class="math display">\[H_1: \mu \neq \mu_0\]</span></p>
<p>but need to specify a <strong>minimum detectable difference</strong>, often called <span class="math inline">\(\delta=μ_1−μ_0\)</span> such that we reject <span class="math inline">\(H_0\)</span> with a certain power (usually 80% or 90%) when in fact <span class="math inline">\(μ=μ_1\)</span>. We will need a bigger sample size when <span class="math inline">\(\delta\)</span> is small, and fewer subjects when <span class="math inline">\(\delta\)</span> is larger.</p>
</section>
<section id="sample-size-for-for-two-sided-one-sample-test-of-mean" class="slide level2 smaller">
<h2>Sample size for for two-sided one-sample test of mean</h2>
<ul>
<li><p>Power and sample size are interrelated.</p></li>
<li><p>Ideally, when we plan a study, we have a prespecified idea of the minimum difference we want to detect, <span class="math inline">\(δ=μ_1−μ_0\)</span>, the standard deviation, <span class="math inline">\(\sigma\)</span>, and the power, <span class="math inline">\(1-\beta\)</span>, we’d like to have to detect it. In that case, it is straightforward to calculate the required sample size (here given for a one-sample test):</p></li>
</ul>
<p><span class="math display">\[n = \left[ \frac{\sigma (z^*_{1-\alpha/2} + z^*_{1-\beta})}{\mu_1-\mu_0}\right]^2\]</span></p>
<ul>
<li>This can be derived from looking at the rejection regions when <span class="math inline">\(H_0\)</span> and <span class="math inline">\(H_1\)</span> are true, though the details are outside the scope of this class.</li>
<li>You can easily calculate power and sample size in R.</li>
</ul>
</section>
<section id="case-study-ultra-low-dose-contraception" class="slide level2 smaller">
<h2>Case study: ultra low dose contraception</h2>
<ul>
<li><p>Suppose you want to ensure a new manufacturer of birth control pills provides the correct dosage of 0.02 <span class="math inline">\(\mu\)</span>g estrogen.</p></li>
<li><p>How many pills do you need to sample in a shipment in order to ensure 80% power to detect a difference of 10% at <span class="math inline">\(\alpha\)</span>=0.05, assuming <span class="math inline">\(\sigma\)</span>=0.008? (10% of 0.02 is 0.002)</p></li>
</ul>
<p><span class="math display">\[n = \left[\frac{\sigma(z^*_{1-\alpha/2} + z^*_{1-\beta})}{\mu_1-\mu_0}\right]^2\]</span></p>
<p>What are <span class="math inline">\(z^*_{1-\alpha/2}\)</span> and <span class="math inline">\(z^*_{1-\beta}\)</span>? These are the <span class="math inline">\(1-\alpha\)</span> and <span class="math inline">\(1-\beta\)</span> quantile cutoffs of a Z-distribution.</p>
</section>
<section id="z-cutoffs-in-r" class="slide level2">
<h2>Z cutoffs in R</h2>
<ul>
<li><p><span class="math inline">\(\alpha = 0.05\)</span></p></li>
<li><p>Power = 80%, so Type 2 error rate is 1-.80 = .20 = <span class="math inline">\(\beta\)</span>.</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href=""></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span> <span class="co"># type 1 error rate</span></span>
<span id="cb7-2"><a href=""></a>beta <span class="ot">&lt;-</span> .<span class="dv">20</span> <span class="co"># type 2 error rate</span></span>
<span id="cb7-3"><a href=""></a><span class="fu">qnorm</span>(<span class="dv">1</span><span class="sc">-</span>alpha<span class="sc">/</span><span class="dv">2</span>); <span class="fu">qnorm</span>(<span class="dv">1</span><span class="sc">-</span>beta)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.959964</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8416212</code></pre>
</div>
</div>
</section>
<section id="plugging-in-our-values" class="slide level2 smaller">
<h2>Plugging in our values</h2>
<p><span class="math inline">\(= \left[\frac{.008(1.96 + 0.84)}{0.002}\right]^2\)</span></p>
<p><span class="math inline">\(= 125.44\)</span></p>
<p>Using a normal approximation, we would need 126 pills sampled to detect the desired difference of 10%, given <span class="math inline">\(\sigma = 0.008\)</span>, at 80% power.</p>
<ul>
<li>To be conservative, always <strong>round up for sample size calculations</strong>.</li>
</ul>
</section>
<section id="we-use-the-t-distribution-in-practice" class="slide level2">
<h2>We use the t-distribution in practice</h2>
<ul>
<li><p>In the example above, we used the z-distribution. However, we use the <span class="math inline">\(t\)</span> distribution in practice instead of the <span class="math inline">\(z\)</span>.</p></li>
<li><p>This is because the population standard deviation (<span class="math inline">\(\sigma\)</span>) is <strong>rarely known</strong>, so we estimate it from the sample.</p></li>
<li><p>The <em>t</em>-distribution accounts for this extra uncertainty.</p></li>
<li><p>When sample sizes are <strong>small or moderate</strong>, using the <em>t</em>-distribution provides more accurate power estimates, since it better reflects the variability from estimating <span class="math inline">\(\sigma\)</span>.</p></li>
</ul>
</section>
<section id="in-r" class="slide level2">
<h2>In R</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href=""></a><span class="fu">power.t.test</span>(<span class="at">delta =</span> <span class="fl">0.002</span>,</span>
<span id="cb10-2"><a href=""></a>             <span class="at">sd =</span> <span class="fl">0.008</span>,</span>
<span id="cb10-3"><a href=""></a>             <span class="at">sig.level =</span> <span class="fl">0.05</span>,</span>
<span id="cb10-4"><a href=""></a>             <span class="at">power =</span> <span class="fl">0.8</span>,</span>
<span id="cb10-5"><a href=""></a>             <span class="at">type =</span> <span class="st">"one.sample"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     One-sample t test power calculation 

              n = 127.5161
          delta = 0.002
             sd = 0.008
      sig.level = 0.05
          power = 0.8
    alternative = two.sided</code></pre>
</div>
</div>
<p>Using the t-distribution, we need 128 pills sampled to detect the desired difference.</p>
</section>
<section id="example-power-calculation" class="slide level2">
<h2>Example: Power Calculation</h2>
<ul>
<li><p>Researchers are testing whether a new low-sodium diet reduces <strong>systolic blood pressure (SBP)</strong> compared to a control diet.</p></li>
<li><p>Previous studies suggest an average reduction of <strong>8 mmHg</strong> with a standard deviation of <strong>10 mmHg</strong>.</p></li>
<li><p>They plan to recruit <strong>20 participants per group</strong> and use a <strong>two-sided t-test</strong> at the 0.05 level.</p></li>
</ul>
<p><strong>Question:</strong> What statistical <em>power</em> will they have to detect this difference?</p>
</section>
<section id="in-r-1" class="slide level2 smaller">
<h2>In R</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href=""></a><span class="co"># Power calculation for two-sample t-test</span></span>
<span id="cb12-2"><a href=""></a><span class="fu">power.t.test</span>(<span class="at">n =</span> <span class="dv">20</span>,                            <span class="co"># sample size of 20 per group</span></span>
<span id="cb12-3"><a href=""></a>             <span class="at">delta =</span> <span class="dv">8</span>,                         <span class="co"># difference between means</span></span>
<span id="cb12-4"><a href=""></a>             <span class="at">sd =</span> <span class="dv">10</span>,                           <span class="co"># pop. standard deviation</span></span>
<span id="cb12-5"><a href=""></a>             <span class="at">sig.level =</span> <span class="fl">0.05</span>,                  <span class="co"># alpha</span></span>
<span id="cb12-6"><a href=""></a>             <span class="at">type =</span> <span class="st">"two.sample"</span>,               <span class="co"># two-sample t test</span></span>
<span id="cb12-7"><a href=""></a>             <span class="at">alternative =</span> <span class="st">"two.sided"</span>)         <span class="co"># two-sided alt. hypothesis</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     Two-sample t test power calculation 

              n = 20
          delta = 8
             sd = 10
      sig.level = 0.05
          power = 0.6933994
    alternative = two.sided

NOTE: n is number in *each* group</code></pre>
</div>
</div>
</section>
<section id="interpretation" class="slide level2">
<h2>Interpretation</h2>
<p><strong>Interpretation</strong>: With 20 participants per group, the study has about 69% power to detect an 8 mmHg difference.</p>
<ul>
<li>In other words, if the true effect exists, there’s roughly a 7-in-10 chance we’ll correctly reject the null hypothesis.</li>
</ul>
</section>
<section id="example-2-sample-size-calculation" class="slide level2">
<h2>Example 2: Sample size calculation</h2>
<ul>
<li><p>Suppose we want to test whether a new medication lowers LDL cholesterol compared to a placebo.</p></li>
<li><p>From pilot data, we expect a difference of 15 mg/dL with a standard deviation of 20 mg/dL.</p></li>
<li><p>We want 90% power at a 0.05 significance level for a two-sided test.</p></li>
</ul>
<p><strong>Question</strong>: How many participants per group are needed?</p>
</section>
<section id="in-r-2" class="slide level2">
<h2>In R</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href=""></a><span class="fu">power.t.test</span>(<span class="at">power =</span> <span class="fl">0.90</span>,</span>
<span id="cb14-2"><a href=""></a>             <span class="at">delta =</span> <span class="dv">15</span>,</span>
<span id="cb14-3"><a href=""></a>             <span class="at">sd =</span> <span class="dv">20</span>,</span>
<span id="cb14-4"><a href=""></a>             <span class="at">sig.level =</span> <span class="fl">0.05</span>,</span>
<span id="cb14-5"><a href=""></a>             <span class="at">type =</span> <span class="st">"two.sample"</span>,</span>
<span id="cb14-6"><a href=""></a>             <span class="at">alternative =</span> <span class="st">"two.sided"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     Two-sample t test power calculation 

              n = 38.34601
          delta = 15
             sd = 20
      sig.level = 0.05
          power = 0.9
    alternative = two.sided

NOTE: n is number in *each* group</code></pre>
</div>
</div>
</section>
<section id="interpretation-1" class="slide level2">
<h2>Interpretation</h2>
<p>39 individuals per group are needed (rounding up) to achieve 90% power to detect a 15 mg/dL difference in LDL cholesterol between treatments.</p>
</section>
<section id="components-of-power-analysis" class="slide level2">
<h2>Components of Power Analysis</h2>

<img data-src="images/lec-15/star-power.png" class="r-stretch"></section>
<section id="motivation-comparisons-of-interest" class="slide level2 smaller">
<h2>Motivation: Comparisons of Interest</h2>
<table class="caption-top">
<colgroup>
<col style="width: 22%">
<col style="width: 24%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th>Predictor Type</th>
<th>Outcome Type</th>
<th>Common Tests / Topics</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Categorical</td>
<td>Categorical</td>
<td>Fisher’s exact test, <span class="math inline">\(\chi^2\)</span> test</td>
</tr>
<tr class="even">
<td>Categorical</td>
<td>Continuous</td>
<td>t-tests, ANOVA, nonparametric alternatives</td>
</tr>
<tr class="odd">
<td>Continuous</td>
<td>Continuous</td>
<td>Correlation*, regression **</td>
</tr>
<tr class="even">
<td>Continuous</td>
<td>Categorical</td>
<td>Logistic regression, classification **</td>
</tr>
<tr class="odd">
<td>Other / Complex</td>
<td>Various (e.g.&nbsp;survival, counts)</td>
<td>Advanced or “exotic” methods **</td>
</tr>
</tbody>
</table>
<p>* = covering today</p>
<p>** = covering in upcoming lectures</p>
</section>
<section id="remember-this-plot" class="slide level2">
<h2>Remember this plot?</h2>

<img data-src="lec-12-power_MH_files/figure-revealjs/unnamed-chunk-10-1.png" alt="A scatterplot with the x-axis labeled Adequate aerobic activity (%) and the y-axis labeled Obesity (%); the dots follow roughly a downward line" width="960" class="r-stretch"></section>
<section id="some-questions-of-interest-may-include" class="slide level2">
<h2>Some questions of interest may include:</h2>
<ul>
<li><p>Direction of relationship: are variables positively or negatively related?</p></li>
<li><p>Form: is any relationship linear or more complex?</p></li>
<li><p>Strength of relationship: how accurately can one variable predict the other?</p></li>
<li><p>Influential points: are one or a few points driving the relationship we see?</p></li>
</ul>
</section>
<section id="correlation" class="slide level2">
<h2>Correlation</h2>
<ul>
<li><p>The <strong>correlation coefficient</strong> <span class="math inline">\(\rho\)</span> quantifies the <em>linear relationship</em> between two random variables.</p></li>
<li><p>In statistics, a correlation coefficient implies a very specific type of association.</p></li>
<li><p>A correlation coefficient of zero does NOT imply no relationship between two variables, as we shall see in some further examples.</p></li>
</ul>
</section>
<section id="correlation-1" class="slide level2">
<h2>Correlation</h2>
<p><span class="math inline">\(\rho\)</span> ranges from -1 to 1</p>
<ul>
<li><p><span class="math inline">\(\rho&gt;0\)</span> implies positive correlation</p></li>
<li><p><span class="math inline">\(\rho &lt; 0\)</span> implies negative correlation</p></li>
<li><p><span class="math inline">\(\rho = 0\)</span> is consistent with no <em>linear</em> relationship between variables (again, this does not imply that no relationship exists!)</p></li>
</ul>
<p>What does it mean to have a correlation of -1 or 1?</p>
</section>
<section id="visualizing-rho" class="slide level2">
<h2>Visualizing <span class="math inline">\(\rho\)</span></h2>

<img data-src="lec-12-power_MH_files/figure-revealjs/unnamed-chunk-11-1.png" alt="Two scatterplots side-by-side. The one on the left is titled Correlation of 0.6 and the dots are not closely grouped, but generally the y value seems to increase when the x value increases. The one on the right is titled Correlation of 1 and the dots perfectly follow the line x = y." width="960" class="r-stretch"></section>
<section id="visualizing-rho-1" class="slide level2">
<h2>Visualizing <span class="math inline">\(\rho\)</span></h2>

<img data-src="lec-12-power_MH_files/figure-revealjs/unnamed-chunk-12-1.png" alt="Two scatterplots side-by-side. The one on the left is titled Correlation of -0.2 and the dots are not closely grouped, but there is a slight downward trend. The one on the right is titled Correlation of -0.8 and the dots are more closely grouped than on the left and show a clear downward trend." width="960" class="r-stretch"></section>
<section id="visualizing-rho-2" class="slide level2">
<h2>Visualizing <span class="math inline">\(\rho\)</span></h2>

<img data-src="lec-12-power_MH_files/figure-revealjs/unnamed-chunk-13-1.png" alt="Two scatterplots side-by-side. The one on the left is titled Correlation of 0 and the dots are randomly scatted. The one on the right is titled Correlation of 0 and the dots follow a parabola." width="960" class="r-stretch"></section>
<section id="pearsons-correlation-coefficient" class="slide level2 smaller">
<h2>Pearson’s correlation coefficient</h2>
<p><strong>Pearson’s correlation</strong> <span class="math inline">\(r\)</span> gives and estimate of <span class="math inline">\(\rho\)</span> as follows. Assuming our observed data are the pairs <span class="math inline">\((x_1, y_1), (x_2, y_2), \ldots, (x_n, y_n)\)</span>, we can calculate <span class="math inline">\(r\)</span> as</p>
<p><span class="math display">\[r = \frac{1}{n} \sum_{i=1}^n \left(\frac{x_i - \bar{X}}{S_x}\right)\left(\frac{y_i - \bar{Y}}{S_y}\right)\]</span></p>
<p><span class="math display">\[= \frac{\sum_{i=1}^n (x_i - \bar{X})(y_i - \bar{Y})}{\sqrt{\sum_{i=1}^n (x_i - \bar{X})^2\sum_{i=1}^n(y_i - \bar{Y})^2}}\]</span></p>
<p>No need to memorize this!…we’ll just use the <code>cor()</code> function to calculate it in R.</p>
</section>
<section id="anscombes-quartet" class="slide level2">
<h2>Anscombe’s quartet</h2>

<img data-src="images/lec-16/anscombe.png" alt="Four plots, each with 11 dots. The upper left plot has the dots clustered in an upward line; the upper right plot has the dots forming a parabolic shape; the lower left has ten of the dots in a line with slope of about 0.4 and one upwards of the line; and the lower right has ten dots at x=8 ranging from y = 5 to y = 9, and one dot at x=19 and y = 12. All four plots have a blue line that intersects the y-axis at around y = 4 with the same slope." class="r-stretch"></section>
<section id="anscombes-quartet-1" class="slide level2">
<h2>Anscombe’s quartet</h2>
<p>In each of the datasets the following statistical summaries hold:</p>
<ul>
<li><p>mean of <code>x</code>: 9</p></li>
<li><p>variance of <code>x</code>: 11</p></li>
<li><p>mean of <code>y</code>: 7.5</p></li>
<li><p>variance of <code>y</code>: 4.125</p></li>
<li><p>correlation between <code>x</code> and <code>y</code>: 0.816</p></li>
</ul>
</section>
<section id="takeaway" class="slide level2">
<h2>Takeaway</h2>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p><strong>Takeaway</strong>: Visualizing your data is important! Summary statistics alone cannot capture the full relationship between <code>x</code> and <code>y</code>.</p>
</div>
</div>
</div>
<p>Also, <a href="https://github.com/jumpingrivers/datasauRus">Datasaurus Dozen</a>!</p>
</section>
<section id="correlation-does-not-imply-causation" class="slide level2">
<h2>Correlation does not imply causation</h2>

<img data-src="images/lec-16/spur.png" alt="A graph with the title Solar power generated in Belize correlates with The number of fire inspectors in Fdlorida. The lefthand y-axis is labeled Billion kilowatt hours, the righthand y-axis is labeled Laborers, and the x-axis has the years 2003 to 2021. A black line shows the total solar power generated in belize, which is very low for 2003- 2018, then jumps to 0.01 billion kwh in 2019. A red line shows the number of fire inspectors in Florida, which is relatively constant at about 900 from 2003 to 2018, then jumps to 2400 in 2019. The lines closely overlap." class="r-stretch"><p>Source: Tyler Vigen, <a href="http://www.tylervigen.com/spurious-correlations">Spurious Correlations</a></p>
</section>
<section id="confounding" class="slide level2">
<h2>Confounding</h2>
<ul>
<li><p>Many of these spurious correlations are due to <strong>confounding</strong> - when a third lurking variable is responsible for the observed relationship.</p></li>
<li><p>Example: A near perfect negative correlation (r = -0.99) was seen between cholera mortality and elevation above sea level during a 19th century epidemic.</p></li>
<li><p>The observed relationship between cholera and elevation was confounded by a lurking variable, proximity to polluted water.</p></li>
</ul>
</section>
<section id="ggcorrplot" class="slide level2">
<h2>ggcorrplot</h2>
<ul>
<li><p><code>ggcorrplot</code> is a fantastic function for making correlation plots in R.</p></li>
<li><p>This function is in the <code>ggcorrplot</code> package.</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href=""></a><span class="fu">library</span>(ggcorrplot)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li>Let’s check out <a href="https://cran.r-project.org/web/packages/ggcorrplot/readme/README.html">some examples</a>.</li>
</ul>
</section>
<section id="example" class="slide level2">
<h2>Example</h2>
<ul>
<li><p><code>mtcars</code> is a built-in R dataset, taken from the 1974 Motor Trend US magazine. It has fuel consumption and 10 aspects of automobile design/performance for 32 automobiles.</p></li>
<li><p><code>mtcars</code> is built <strong>into</strong> R, and I can just load the dataset</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href=""></a><span class="co"># Loading the dataset mtcars</span></span>
<span id="cb17-2"><a href=""></a><span class="fu">data</span>(mtcars)</span>
<span id="cb17-3"><a href=""></a><span class="co">#Looking at first 5 variables for the first few observations</span></span>
<span id="cb17-4"><a href=""></a><span class="fu">head</span>(mtcars[, <span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   mpg cyl disp  hp drat
Mazda RX4         21.0   6  160 110 3.90
Mazda RX4 Wag     21.0   6  160 110 3.90
Datsun 710        22.8   4  108  93 3.85
Hornet 4 Drive    21.4   6  258 110 3.08
Hornet Sportabout 18.7   8  360 175 3.15
Valiant           18.1   6  225 105 2.76</code></pre>
</div>
</div>
</section>
<section id="example-1" class="slide level2">
<h2>Example</h2>
<ul>
<li><code>mtcars</code> is a built-in R dataset, taken from the 1974 Motor Trend US magazine. It has fuel consumption and 10 aspects of automobile design/performance for 32 automobiles.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href=""></a><span class="co"># Compute a correlation matrix</span></span>
<span id="cb19-2"><a href=""></a><span class="fu">data</span>(mtcars)</span>
<span id="cb19-3"><a href=""></a>corr <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">cor</span>(mtcars), <span class="dv">1</span>) <span class="co"># round to 1 decimal</span></span>
<span id="cb19-4"><a href=""></a><span class="fu">head</span>(corr[, <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      mpg  cyl disp   hp drat   wt
mpg   1.0 -0.9 -0.8 -0.8  0.7 -0.9
cyl  -0.9  1.0  0.9  0.8 -0.7  0.8
disp -0.8  0.9  1.0  0.8 -0.7  0.9
hp   -0.8  0.8  0.8  1.0 -0.4  0.7
drat  0.7 -0.7 -0.7 -0.4  1.0 -0.7
wt   -0.9  0.8  0.9  0.7 -0.7  1.0</code></pre>
</div>
</div>
</section>
<section id="plotting-the-correlation-code" class="slide level2">
<h2>Plotting the correlation: code</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href=""></a><span class="co"># Visualize the correlation matrix</span></span>
<span id="cb21-2"><a href=""></a><span class="co"># --------------------------------</span></span>
<span id="cb21-3"><a href=""></a><span class="co"># method = "square" (default)</span></span>
<span id="cb21-4"><a href=""></a><span class="fu">ggcorrplot</span>(corr)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="plotting-the-correlation-output" class="slide level2">
<h2>Plotting the correlation: output</h2>

<img data-src="lec-12-power_MH_files/figure-revealjs/unnamed-chunk-18-1.png" alt="An 11 by 11 grid, with the rows and columns of the grid labeled with the eleven variables in the m t cars data set. The squares of the grid are colored on a gradient from -1 to 1, where dark blue corresponds to -1, white corresponds to 0, and red corresponds to 1; this is shown in the legend labeled Correlation. The squares where the row and column have the same label are bright red." width="960" class="r-stretch"></section>
<section id="testing-the-correlation" class="slide level2">
<h2>Testing the correlation</h2>
<ul>
<li>We can also test whether or not each correlation is statistically equal to zero.</li>
</ul>
<p><span class="math display">\[H_0: \rho = 0 \quad \text{vs.} \quad H_A: \rho \neq 0\]</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href=""></a><span class="co"># Compute a matrix of correlation p-values</span></span>
<span id="cb22-2"><a href=""></a>p.mat <span class="ot">&lt;-</span> <span class="fu">cor_pmat</span>(mtcars)</span>
<span id="cb22-3"><a href=""></a><span class="fu">head</span>(p.mat[, <span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>              mpg          cyl         disp           hp
mpg  0.000000e+00 6.112687e-10 9.380327e-10 1.787835e-07
cyl  6.112687e-10 0.000000e+00 1.802838e-12 3.477861e-09
disp 9.380327e-10 1.802838e-12 0.000000e+00 7.142679e-08
hp   1.787835e-07 3.477861e-09 7.142679e-08 0.000000e+00
drat 1.776240e-05 8.244636e-06 5.282022e-06 9.988772e-03
wt   1.293959e-10 1.217567e-07 1.222320e-11 4.145827e-05</code></pre>
</div>
</div>
</section>
<section id="example-code" class="slide level2">
<h2>Example: code</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href=""></a><span class="fu">ggcorrplot</span>(p.mat)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="lec-12-power_MH_files/figure-revealjs/unnamed-chunk-20-1.png" alt="An 11 by 11 grid as before, but with mostly white squares, with a scattering of light red and medium red squares in the upper righthand corner." width="960" class="r-stretch"></section>
<section id="r-graph-gallery" class="slide level2">
<h2>R Graph Gallery</h2>
<p><a href="https://r-graph-gallery.com/">R Graph Gallery</a> has lots of examples, with code!</p>
<ul>
<li>Along with many other types of plots.</li>
</ul>
</section>
<section id="a-note-on-karl-pearson" class="slide level2">
<h2>A Note on Karl Pearson</h2>
<ul>
<li><p>Karl Pearson was an English biostatistician who established the field of mathematical statistics as we know it today.</p></li>
<li><p>The correlation coefficient we talked about today is named after him; you may have also noticed that the chi-squared test is sometimes called Pearson’s chi-squared test (like it is in R output).</p></li>
</ul>
<div class="fragment">
<ul>
<li><p>Pearson, like Fisher, was a eugenicist (he founded the journal <em>The Annals of Eugenics</em>), and many of his beliefs are what is now categorized as scientific racism.</p></li>
<li><p>In 2020, University College London renamed two buildings previously named in his honor.</p></li>
</ul>
</div>
</section>
<section id="next-class" class="slide level2">
<h2>Next Class</h2>
<ul>
<li>Review for Exam 2</li>
</ul>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="images/logo_600.png" class="slide-logo"></p>
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="lec-12-power_MH_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="lec-12-power_MH_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="lec-12-power_MH_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="lec-12-power_MH_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="lec-12-power_MH_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="lec-12-power_MH_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="lec-12-power_MH_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="lec-12-power_MH_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="lec-12-power_MH_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="lec-12-power_MH_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: false,

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>