<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Lecture 8: Confidence Intervals and Hypothesis Testing</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="lec-9-ci-hypo-anno_MH_files/libs/clipboard/clipboard.min.js"></script>
<script src="lec-9-ci-hypo-anno_MH_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="lec-9-ci-hypo-anno_MH_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="lec-9-ci-hypo-anno_MH_files/libs/quarto-html/popper.min.js"></script>
<script src="lec-9-ci-hypo-anno_MH_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="lec-9-ci-hypo-anno_MH_files/libs/quarto-html/anchor.min.js"></script>
<link href="lec-9-ci-hypo-anno_MH_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="lec-9-ci-hypo-anno_MH_files/libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="lec-9-ci-hypo-anno_MH_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="lec-9-ci-hypo-anno_MH_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="lec-9-ci-hypo-anno_MH_files/libs/bootstrap/bootstrap-138a6193a3bd40baf1e627da441a4734.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Lecture 8: Confidence Intervals and Hypothesis Testing</h1>
<p class="subtitle lead">BIOS 600 - Summer Session II 2026</p>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Authors</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
  </div>

<div class="quarto-title-meta">

      
  
    
  </div>
  


</header>


<section id="announcements" class="level2">
<h2 class="anchored" data-anchor-id="announcements">Announcements</h2>
<ul>
<li><p>HW 7 is due <strong>tonight</strong> at 11:59 PM</p></li>
<li><p>HW 8 will be due <strong>tomorrow</strong> at 11:59 PM</p></li>
</ul>
</section>
<section id="overview" class="level2">
<h2 class="anchored" data-anchor-id="overview">Overview</h2>
<ul>
<li><p>Using a t-distribution vs.&nbsp;a z-distribution to create confidence intervals</p></li>
<li><p><code>qt()</code> function</p></li>
<li><p>Hypothesis tests: how to conduct them, how to interpret them</p></li>
</ul>
</section>
<section id="readings" class="level2">
<h2 class="anchored" data-anchor-id="readings">Readings</h2>
<ul>
<li><p>P &amp; G: Chapter 9, Chapter 10.1 - 10.4</p></li>
<li><p>OpenIntro: 5.3</p></li>
</ul>
</section>
<section id="another-example-of-interpreting-a-ci" class="level2">
<h2 class="anchored" data-anchor-id="another-example-of-interpreting-a-ci">Another Example of Interpreting a CI</h2>
<p>A study estimates the mean systolic blood pressure of adults with diabetes as 132 mmHg, with a 95% confidence interval of [128, 136]</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>How would you interpret this confidence interval?</p>
</div>
</div>
</section>
<section id="ci-interpretation" class="level2">
<h2 class="anchored" data-anchor-id="ci-interpretation">CI interpretation</h2>
<p>Is this interpretation correct?</p>
<p>“There is a 95% chance that the true mean SBP lies in the interval”</p>
<p>This is <strong>incorrect</strong>!</p>
<ul>
<li><p><strong>Important</strong>: we <strong>do not know</strong> whether any particular interval is in the 95% of them that cover the mean or the 5% that don’t</p></li>
<li><p>Since <span class="math inline">\(\mu\)</span> is a parameter, it’s either in our confidence interval or not</p></li>
</ul>
</section>
<section id="ci-interpretation-1" class="level2">
<h2 class="anchored" data-anchor-id="ci-interpretation-1">CI interpretation</h2>
<ul>
<li><p>Let’s say I <strong>know</strong> 54% of the population of NC is going to vote for Candidate A, and two polls of 400 individuals are done. One poll estimates 50% with a 95% CI of (0.45, 0.55) and a second poll estimates 60% with a 95% CI of (0.55, 0.65)</p></li>
<li><p>The <strong>true proportion</strong> voting for Candidate A does not change it is either included or not included in each interval - there isn’t a chance of this being in either interval</p></li>
<li><p>But. . . if I did this poll many many times, constructing a 95% confidence interval each time in the same way, then about 95% of those intervals would contain the true proportion of the population voting for candidate A</p></li>
</ul>
</section>
<section id="when-can-we-use-this-ci" class="level2">
<h2 class="anchored" data-anchor-id="when-can-we-use-this-ci">When can we use this CI?</h2>
<div class="poll">
<p><span class="math display">\[(\bar X - z^* \frac{\sigma}{\sqrt n}, \bar X + z^* \frac{\sigma}{\sqrt n})\]</span></p>
</div>
<p>Remember, this is only ok to use when <span class="math inline">\(\sigma\)</span> is known, and:</p>
<ul>
<li><span class="math inline">\(X\)</span> is normal</li>
<li><span class="math inline">\(X\)</span> is non-normal, but <span class="math inline">\(n\)</span> is sufficiently large</li>
</ul>
</section>
<section id="what-can-we-do-if-sigma-isnt-known" class="level2">
<h2 class="anchored" data-anchor-id="what-can-we-do-if-sigma-isnt-known">What can we do if <span class="math inline">\(\sigma\)</span> isn’t known?</h2>
<div class="columns">
<div class="column" style="width:40%;">
<p><img src="images/lec-9/will.jpg" class="img-fluid" alt="A photo of William Sealy Gossett, wearing a suit. He has a mustache."></p>
</div><div class="column" style="width:60%;">
<ul>
<li><p>As a Guiness brewery employee, William Sealy Gossett published a paper on the <span class="math inline">\(t\)</span> distribution, which became known as Student’s <span class="math inline">\(t\)</span> (the brewery didn’t allow him to use his own name)</p></li>
<li><p>A. Student. <em>The probable error of a mean</em> (1908)</p></li>
</ul>
</div>
</div>
</section>
<section id="students-t-distribution" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="students-t-distribution">Student’s <span class="math inline">\(t\)</span> distribution</h2>
<div class="columns">
<div class="column" style="width:40%;">
<ul>
<li><p>Gosset used his new distribution to determine how large a sample should be for testing beer</p></li>
<li><p>The <span class="math inline">\(t\)</span> distribution is appropriate for constructing a confidence interval for the mean when <span class="math inline">\(\sigma\)</span> is unknown</p></li>
</ul>
</div><div class="column" style="width:60%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lec-9-ci-hypo-anno_MH_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid figure-img" alt="A graph titled Comparison of t-Distributions with five curves: a dashed black curve represents the standard normal distribution, a yellow curve the t distribution with 30 degrees of freedom, a green curve the t distribution with 10 degrees of freedom, a blue curve the t distribution with 3 degrees of freedom, and a red curve the t distribution with 1 degree of freedom. As the degrees of freedom decrease, the t distribution curves become flatter than the normal curve, with wider tails." width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="students-t-distribution-1" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="students-t-distribution-1">Student’s <span class="math inline">\(t\)</span> distribution</h2>
<div class="columns">
<div class="column" style="width:40%;">
<ul>
<li><p>The <span class="math inline">\(t\)</span> distribution looks like the normal distribution except it has thicker tails, leading to wider CIs</p></li>
<li><p>This is due to the uncertainty involved in estimating <span class="math inline">\(\sigma\)</span> by using <span class="math inline">\(s\)</span> (the standard deviation of the sample)</p></li>
<li><p>As the sample size increases, <span class="math inline">\(s\)</span> is a better and better estimate of <span class="math inline">\(\sigma\)</span>, and so the <span class="math inline">\(t\)</span> distribution looks more and more like the normal distribution</p></li>
</ul>
</div><div class="column" style="width:60%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lec-9-ci-hypo-anno_MH_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" alt="A graph titled Comparison of t-Distributions with five curves: a dashed black curve represents the standard normal distribution, a yellow curve the t distribution with 30 degrees of freedom, a green curve the t distribution with 10 degrees of freedom, a blue curve the t distribution with 3 degrees of freedom, and a red curve the t distribution with 1 degree of freedom. As the degrees of freedom decrease, the t distribution curves become flatter than the normal curve, with wider tails." width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="degrees-of-freedom" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="degrees-of-freedom">Degrees of freedom</h2>
<ul>
<li>The <strong>degrees of freedom</strong> of a <span class="math inline">\(t\)</span> distribution tells us how much information is “available” for estimating <span class="math inline">\(\sigma\)</span> using <span class="math inline">\(s\)</span>. The random variable</li>
</ul>
<div class="poll">
<p><span class="math display">\[t = \frac{\bar X - \mu}{s/ \sqrt{n}}\]</span></p>
</div>
<p>has a <span class="math inline">\(t\)</span> distribution with <span class="math inline">\(n-1\)</span> degrees of freedom (<span class="math inline">\(df\)</span>), which we denote by <span class="math inline">\(t_{n-1}\)</span> (we lose one <span class="math inline">\(df\)</span> by estimating the sample mean using <span class="math inline">\(\bar X\)</span>).</p>
<ul>
<li><p>The <span class="math inline">\(t\)</span> distribution only has one parameter (<span class="math inline">\(df\)</span>)</p></li>
<li><p>How does this compare to the standard normal distribution?</p></li>
</ul>
</section>
<section id="two-sided-interval-with-unknown-sigma" class="level2">
<h2 class="anchored" data-anchor-id="two-sided-interval-with-unknown-sigma">Two-sided interval with unknown <span class="math inline">\(\sigma\)</span></h2>
<ul>
<li>When we do not know <span class="math inline">\(\sigma\)</span> (which is pretty much always), we can use the following interval:</li>
</ul>
<div class="poll">
<p><span class="math display">\[(\bar X - t^*_{n-1; 1-\alpha/2} \frac{s}{\sqrt n}, \bar X + t^*_{n-1; 1-\alpha/2} \frac{s}{\sqrt n})\]</span></p>
</div>
<ul>
<li><p>In practice, if <span class="math inline">\(\sigma\)</span> is unknown, we use the t-distribution no matter the sample size.</p></li>
<li><p>For very large <span class="math inline">\(n\)</span>, the difference between t and z disappears, so either works — but conventionally we stick with t.</p></li>
</ul>
</section>
<section id="finding-critical-values-for-t-distribution" class="level2">
<h2 class="anchored" data-anchor-id="finding-critical-values-for-t-distribution">Finding critical values for t-distribution</h2>
<ul>
<li><p>For the <span class="math inline">\(t^*\)</span> distribution</p></li>
<li><p>R provides two functions:</p>
<ul>
<li><code>pt()</code> → cumulative probability (area to the left)</li>
<li><code>qt()</code> → quantile function (finds cutoff given probability)</li>
</ul></li>
<li><p>These are analogous to <code>pnorm()</code> and <code>qnorm()</code>, but instead of a mean and sd, you put the degrees of freedom in the parentheses</p></li>
</ul>
</section>
<section id="example-code" class="level2">
<h2 class="anchored" data-anchor-id="example-code">Example code</h2>
<p>Suppose we want a 95% confidence interval with <span class="math inline">\(n = 20\)</span> observations:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">20</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># degrees of freedom</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> n <span class="sc">-</span> <span class="dv">1</span>  </span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># t critical value</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>t_crit <span class="ot">&lt;-</span> <span class="fu">qt</span>(<span class="dv">1</span> <span class="sc">-</span> alpha<span class="sc">/</span><span class="dv">2</span>, <span class="at">df =</span> df)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>t_crit</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.093024</code></pre>
</div>
</div>
<ul>
<li>This is the cutoff value such that 95% of the <span class="math inline">\(t_{19}\)</span> distribution lies between <span class="math inline">\(-t\)</span> and <span class="math inline">\(+t\)</span>.</li>
</ul>
</section>
<section id="t-critical-values" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="t-critical-values"><span class="math inline">\(t\)</span> critical values</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lec-9-ci-hypo-anno_MH_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" alt="A graph with title T-distribution with 19 degrees of freedom. There are three curves, a black dashed one representing the standard normal distribution, a red one for the t-distribution with 19 degrees of freedom, and a blue one for the t-distribution with 1 degree of freedom. The red curve is similar to the black dashed curve, with slightly wider tails; the blue curve has much wider tails and is not as high-valued at the mean x= 0." width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="two-sided-interval-with-unknown-sigma-1" class="level2">
<h2 class="anchored" data-anchor-id="two-sided-interval-with-unknown-sigma-1">Two-sided interval with unknown <span class="math inline">\(\sigma\)</span></h2>
<ul>
<li>For n = 20 and <span class="math inline">\(\alpha=0.05\)</span>, <span class="math inline">\(t^*_{n-1; 1-\alpha/2}=t^*_{19; 1-\alpha/2}=2.09\)</span></li>
</ul>
<p><span class="math display">\[(\bar X - 2.09 \frac{s}{\sqrt n}, \bar X + 2.09 \frac{s}{\sqrt n})\]</span></p>
<ul>
<li>How does this compare to confidence multiplier of <span class="math inline">\(z^*_{1-\alpha/2}\)</span>?</li>
</ul>
</section>
<section id="what-about-one-sided-intervals" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="what-about-one-sided-intervals">What about one-sided intervals?</h2>
<ul>
<li><p>The symmetric two-sided confidence intervals we have dealt with so far give the shortest intervals with the desired coverage probability (for symmetric distributions)</p></li>
<li><p>Occasionally, we may only want an upper limit or a lower limit for the population mean, for instance in a non-inferiority clinical trial for a generic drug (we don’t expect the generic drug to work better, but we do expect it to be “not worse”)</p></li>
<li><p>We won’t focus on these in this class.</p></li>
</ul>
</section>
<section id="remember-iq-example" class="level2">
<h2 class="anchored" data-anchor-id="remember-iq-example">Remember IQ example?</h2>
<ul>
<li><p>IQ tests have a distribution with <span class="math inline">\(\mu\)</span> = 100 and <strong>known</strong> <span class="math inline">\(\sigma\)</span> = 15</p></li>
<li><p>For a random sample of <span class="math inline">\(n = 30\)</span>, BIOS 600 students, the sample average IQ score is 120</p></li>
<li><p>The central limit theorem tells us that the distribution of means of samples of size 30 from this population is also normal, with mean <span class="math inline">\(\mu = 100\)</span> and <span class="math inline">\(SE = \sigma/ \sqrt{n} = 15 \sqrt{30} \approx 2.7\)</span></p></li>
</ul>
</section>
<section id="remember-iq-example-1" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="remember-iq-example-1">Remember IQ example?</h2>
<ul>
<li>Remember here I <strong>know</strong> <span class="math inline">\(\sigma\)</span>, I can derive 95% confidence interval for the BIOS 600 students’ average IQ</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="dv">1</span><span class="sc">-</span>(alpha<span class="sc">/</span><span class="dv">2</span>), <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.959964</code></pre>
</div>
</div>
<p><span class="math display">\[(120 - 1.96 *\frac{15}{\sqrt 30}, 120 + 1.96 * \frac{15}{\sqrt 30}) = (114.6, 125.4)\]</span></p>
<ul>
<li>I am 95% confident the true mean IQ for Bios 600 students falls between 114.6 and 125.4</li>
</ul>
</section>
<section id="lets-say-i-dont-know-sigma" class="level2">
<h2 class="anchored" data-anchor-id="lets-say-i-dont-know-sigma">Let’s say I don’t know sigma</h2>
<ul>
<li>Let’s say for a random sample of <span class="math inline">\(n = 30\)</span>, BIOS 600 students, the sample average IQ score is 120 with <strong>sample</strong> standard deviation of 15. I can still derive 95% confidence interval for the BIOS 600 students average IQ using the t-distribution:</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">30</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co"># degrees of freedom</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> n <span class="sc">-</span> <span class="dv">1</span>  </span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="co"># t critical value</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>t_crit <span class="ot">&lt;-</span> <span class="fu">qt</span>(<span class="dv">1</span> <span class="sc">-</span> alpha<span class="sc">/</span><span class="dv">2</span>, <span class="at">df =</span> df)</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>t_crit</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.04523</code></pre>
</div>
</div>
</section>
<section id="remember-iq-example-2" class="level2">
<h2 class="anchored" data-anchor-id="remember-iq-example-2">Remember IQ example?</h2>
<ul>
<li>I have 95% confidence that the true mean IQ for BIOS 600 students is between 114.4 and 125.6</li>
</ul>
<p><span class="math display">\[(120 - 2.045 *\frac{15}{\sqrt 30}, 120 + 2.045 * \frac{15}{\sqrt 30}) = (114.4, 125.6)\]</span></p>
</section>
<section id="remember-iq-example-3" class="level2">
<h2 class="anchored" data-anchor-id="remember-iq-example-3">Remember IQ example?</h2>
<ul>
<li><p>Let’s go back to knowing <span class="math inline">\(\sigma\)</span>, what if I want to test whether BIOS 600 students are smarter than average?</p></li>
<li><p><span class="math inline">\(Z = \frac{\bar{X} - \mu}{SE}\)</span> is a standard normal random variable</p></li>
<li><p><span class="math inline">\(Z \approx 7.3\)</span></p></li>
</ul>
</section>
<section id="how-can-we-answer-research-questions-using-statistics" class="level2">
<h2 class="anchored" data-anchor-id="how-can-we-answer-research-questions-using-statistics">How can we answer research questions using statistics?</h2>
<ul>
<li><strong>Statistical hypothesis testing</strong> is the procedure that assesses evidence provided by the data in favor of or against some claim about the population (often about a population parameter or potential associations).</li>
</ul>
</section>
<section id="the-hypothesis-testing-framework" class="level2">
<h2 class="anchored" data-anchor-id="the-hypothesis-testing-framework">The hypothesis testing framework</h2>
<ol type="1">
<li><p>Start with two hypotheses about the population: the <strong>null hypothesis</strong> and the <strong>alternative hypothesis</strong></p></li>
<li><p>Choose a sample, collect data, and analyze the data</p></li>
<li><p>Figure out how likely it is to see data like what we got/observed, <strong><em>if</em></strong> the null hypothesis were true</p></li>
<li><p>If our data would have been extremely unlikely if the null claim were true, then we reject it and deem the alternative claim worthy of further study. Otherwise, we <strong>cannot reject the null</strong> claim</p></li>
</ol>
</section>
<section id="example-ultra-low-dose-contraception" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="example-ultra-low-dose-contraception">Example: Ultra-low dose contraception</h2>
<ul>
<li><p>Oral contraceptive pills work well, but must have a precise dose of estrogen.</p></li>
<li><p>If a pill has too high a dose, then people may risk side effects such as headaches, nausea, and rare but potentially fatal blood clots</p></li>
<li><p>If a pill has too low a dose, pregnancy may occur</p></li>
</ul>
</section>
<section id="ultra-low-dose-contraception" class="level2">
<h2 class="anchored" data-anchor-id="ultra-low-dose-contraception">Ultra-low dose contraception</h2>
<ul>
<li><p>A certain contraceptive pill is supposed to contain precisely 0.020 <span class="math inline">\(\mu g\)</span> of estrogen.</p></li>
<li><p>During quality control, 50 randomly selected pills are tested, with a sample mean dose 0.017 <span class="math inline">\(\mu g\)</span> and <strong>sample SD</strong> 0.008 <span class="math inline">\(\mu g\)</span>.</p></li>
</ul>
<div class="callout callout-style-simple callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Caution</span>Question
</div>
</div>
<div class="callout-body-container callout-body">
<p>Do you think this is cause for concern? Why or why not?</p>
</div>
</div>
</section>
<section id="two-competing-hypotheses" class="level2">
<h2 class="anchored" data-anchor-id="two-competing-hypotheses">Two competing hypotheses</h2>
<ul>
<li><p>The <strong>null hypothesis</strong> (<span class="math inline">\(H_0\)</span>) states that “nothing unusual is happening” / there is no change from status quo / there is no relationship / etc.</p></li>
<li><p>The <strong>alternative hypothesis</strong> (<span class="math inline">\(H_A\)</span> or <span class="math inline">\(H_1\)</span>) states the opposite: that there is some sort of relationship (usually this is what we want to check or really think is happening)</p></li>
</ul>
<p>Remember, in statistical hypothesis testing we <em>always first assume the null hypothesis is true</em>, and see whether we reject or fail to reject this claim.</p>
</section>
<section id="defining-the-null-and-alternative-hypotheses" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="defining-the-null-and-alternative-hypotheses">Defining the null and alternative hypotheses</h2>
<p>Stated in words:</p>
<ul>
<li><p><span class="math inline">\(H_0\)</span>: The pills are consistent with a population that has a mean of 0.020 <span class="math inline">\(\mu\)</span>g estrogen</p></li>
<li><p><span class="math inline">\(H_1\)</span>: The pills are not consistent with a population that has a mean of 0.020 <span class="math inline">\(\mu\)</span>g estrogen</p></li>
</ul>
<p>Stated in symbols (using LaTeX):</p>
<p><code>$H_0$: $\mu = 0.020$</code> renders to —&gt; <span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu\)</span> = 0.020</p>
<p><code>$H_1$: $\mu \neq 0.020$</code> renders to —&gt; <span class="math inline">\(H_1\)</span>: <span class="math inline">\(\mu \neq\)</span> 0.020</p>
<p>where <span class="math inline">\(\mu\)</span> is the mean estrogen level of the manufactured pills, in <span class="math inline">\(\mu\)</span>g.</p>
</section>
<section id="collecting-and-summarizing-the-data" class="level2">
<h2 class="anchored" data-anchor-id="collecting-and-summarizing-the-data">Collecting and summarizing the data</h2>
<p>With these two hypotheses, we now take a sample and summarize the data</p>
<ul>
<li><p>The choice of <strong>summary statistic</strong> calculated depends on the type of data as well as its distribution.</p></li>
<li><p>In our example, quality control technicians randomly selected a sample of 50 pills and calculated the sample mean <span class="math inline">\(\bar{x}\)</span> = 0.017 <span class="math inline">\(\mu\)</span>g and <strong>sample standard deviation</strong> <span class="math inline">\(s\)</span> = 0.008 <span class="math inline">\(\mu\)</span>g.</p></li>
</ul>
</section>
<section id="collecting-the-data-in-r" class="level2">
<h2 class="anchored" data-anchor-id="collecting-the-data-in-r">Collecting the data in R</h2>
<ul>
<li>(For purposes of this example, we’ve simulated the data with the desired sample size, mean, and sd)</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>df <span class="sc">|&gt;</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  sample_data
1  0.01251619
2  0.01515858
3  0.02946967
4  0.01756407
5  0.01803430</code></pre>
</div>
</div>
</section>
<section id="assessing-the-evidence-observed" class="level2">
<h2 class="anchored" data-anchor-id="assessing-the-evidence-observed">Assessing the evidence observed</h2>
<ul>
<li><p>Next, we calculate the probability of getting data like ours, or more extreme, if <span class="math inline">\(H_0\)</span> were actually true.</p></li>
<li><p>This is a conditional probability: “if <span class="math inline">\(H_0\)</span> were true (i.e., if <span class="math inline">\(\mu\)</span> were truly 0.020), what would be the probability of observing <span class="math inline">\(\bar{x}\)</span> = 0.017 and <span class="math inline">\(s\)</span> = 0.008?</p></li>
<li><p>This probability is the <strong>p-value</strong>.</p></li>
<li><p>P(observing <span class="math inline">\(\bar{x}\)</span> = 0.017 and <span class="math inline">\(s\)</span> = 0.008 | <span class="math inline">\(H_0\)</span> were true)</p></li>
</ul>
</section>
<section id="perform-one-sample-t-test-against-mu-0.020" class="level2">
<h2 class="anchored" data-anchor-id="perform-one-sample-t-test-against-mu-0.020">Perform one-sample t-test against mu = 0.020</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(df<span class="sc">$</span>sample_data, <span class="at">mu =</span> <span class="fl">0.020</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  df$sample_data
t = -2.6012, df = 49, p-value = 0.01225
alternative hypothesis: true mean is not equal to 0.02
95 percent confidence interval:
 0.01517019 0.01938026
sample estimates:
 mean of x 
0.01727523 </code></pre>
</div>
</div>
<ul>
<li>Where does -2.6012 come from?</li>
</ul>
</section>
<section id="two-sided-tests-of-hypotheses" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="two-sided-tests-of-hypotheses">Two-sided tests of hypotheses</h2>
<ul>
<li>To conduct the hypothesis test, we use what we learned about the sampling distribution of the sample mean <span class="math inline">\(\bar{X}\)</span>. If the underlying population is normally distributed (or <span class="math inline">\(n\)</span> is pretty large), then the random variable</li>
</ul>
<div class="poll">
<p><span class="math display">\[t = \frac{\bar{X}-\mu_0}{s/\sqrt{n}}\]</span></p>
</div>
<p>has a <span class="math inline">\(t_{n-1}\)</span> distribution.</p>
</section>
<section id="breaking-down-the-test-statistic" class="level2">
<h2 class="anchored" data-anchor-id="breaking-down-the-test-statistic">Breaking down the test statistic</h2>
<div class="poll">
<p><span class="math display">\[t = \frac{\bar{X}-\mu_0}{s/\sqrt{n}}\]</span></p>
</div>
<ul>
<li><span class="math inline">\(\bar{X} - \mu_0\)</span> tells us how far our sample mean is from the hypothesized population mean</li>
</ul>
<p>Thus, the test statistic <span class="math inline">\(t\)</span> is an estimate of how many SDs apart <span class="math inline">\(\mu_0\)</span> and <span class="math inline">\(\bar{X}\)</span> are from each other</p>
<ul>
<li>Let’s calculate our test statistic using the above formula:</li>
</ul>
</section>
<section id="breaking-down-the-test-statistic-1" class="level2">
<h2 class="anchored" data-anchor-id="breaking-down-the-test-statistic-1">Breaking down the test statistic</h2>
<ul>
<li><p>We have <span class="math inline">\(\bar{X} = 0.017\)</span>, <span class="math inline">\(\mu_0 = 0.020\)</span>, <span class="math inline">\(s = 0.008\)</span>, and <span class="math inline">\(n = 50\)</span>.</p></li>
<li><p>Then <span class="math display">\[t = \frac{0.017 - 0.020}{0.008/\sqrt{50}}\]</span></p></li>
<li><p>This is equal to -2.65165</p></li>
<li><p>Slightly different from before, but that’s because for our simulated data, the mean isn’t <strong>exactly</strong> 0.017 and the standard deviation isn’t <strong>exactly</strong> 0.008</p></li>
</ul>
</section>
<section id="example-conclusion" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="example-conclusion">Example: Conclusion</h2>
<ul>
<li><p>If the true average estrogen level really were 0.020 <span class="math inline">\(\mu\)</span>g, the chance of seeing data this far off just by random luck is about 1 in 100. (P-value = .01225)</p></li>
<li><p>Since that’s very unlikely, we have good evidence the pills’ average estrogen level is not actually 0.020 <span class="math inline">\(\mu\)</span>g.</p></li>
<li><p><strong>Conclusion</strong>: At an alpha level of 0.05, we calculated a p-value of 0.012, which is less than 0.05. There is statistically significant evidence that the mean estrogen level of the manufactured pills is different than 0.020 <span class="math inline">\(\mu\)</span>g.</p></li>
<li><p>In other words: the pills are probably being made with a slightly different average amount of estrogen than intended.</p></li>
</ul>
</section>
<section id="getting-the-p-value-graphically-drawing" class="level2">
<h2 class="anchored" data-anchor-id="getting-the-p-value-graphically-drawing">Getting the p-value graphically (drawing)</h2>
</section>
<section id="breaking-down-the-test-statistic-2" class="level2">
<h2 class="anchored" data-anchor-id="breaking-down-the-test-statistic-2">Breaking down the test statistic</h2>
<ul>
<li><p>The <strong>pt</strong> function is similar to <strong>pnorm</strong></p></li>
<li><p>Probability our observation is the left of 2.6012 is:</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pt</span>(<span class="fl">2.6012</span>, <span class="at">df=</span><span class="dv">49</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9938754</code></pre>
</div>
</div>
<ul>
<li>Probability we observe something as high as 2.6012 or something more extreme</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>p_high <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">-</span><span class="fu">pt</span>(<span class="fl">2.6012</span>, <span class="at">df=</span><span class="dv">49</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>p_high</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.006124635</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span><span class="sc">*</span>p_high</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.01224927</code></pre>
</div>
</div>
</section>
<section id="reflection" class="level2">
<h2 class="anchored" data-anchor-id="reflection">Reflection</h2>
<p><img src="images/lec-10/p-hack_1.png" class="img-fluid" alt="A comic with a poster showing a graph with two boxplots, one for the control group and one for the test group. The poster is labeled p = 0.12 and n = 5, and there is a speech bubble saying We're close to significance. Add a few more replicates and we'll get p less than 0.05"></p>
</section>
<section id="reflection-1" class="level2">
<h2 class="anchored" data-anchor-id="reflection-1">Reflection</h2>
<p><img src="images/lec-10/p-hack_2.png" class="img-fluid" alt="A comic with a poster showing a graph with two boxplots, one for the control group and one for the test group. The poster is labeled p = 0.26 and n = 10, and there is a speech bubble saying What??? Keep adding replicates!"></p>
</section>
<section id="reflection-2" class="level2">
<h2 class="anchored" data-anchor-id="reflection-2">Reflection</h2>
<p><img src="images/lec-10/p-hack_3.png" class="img-fluid" alt="A comic with a poster showing a graph with two boxplots, one for the control group and one for the test group. The poster is labeled p = 0.81 and n = 100, and there is a speech bubble saying OK ... let's do single-cell sequencing instead"></p>
</section>
<section id="but-wait" class="level2">
<h2 class="anchored" data-anchor-id="but-wait">But wait…</h2>
<ul>
<li><p>What if <span class="math inline">\(p \geq \alpha\)</span>?</p></li>
<li><p>We <strong>never</strong> “accept” the null hypothesis – we assumed that <span class="math inline">\(H_0\)</span> was true to begin with and assessed the probability of obtaining our test statistic (or more extreme) under this assumption</p></li>
<li><p>When we fail to reject the null hypothesis, we are stating that there is <em>insufficient evidence</em> to assert that it is false</p></li>
</ul>
</section>
<section id="back-to-iq-example" class="level2">
<h2 class="anchored" data-anchor-id="back-to-iq-example">Back to IQ example</h2>
<ul>
<li><p>Here a sample of 30 students with IQs on average of 120 points. Can we test if the average IQ score for BIOS 600 students is the same as that in the larger population?</p></li>
<li><p><span class="math inline">\(H_0\)</span> = The average IQ score for BIOS 600 students is 100 points.</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># One-sample t-test (greater than 100)</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(bios600, <span class="at">mu =</span> <span class="dv">100</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  bios600
t = 7.1812, df = 29, p-value = 6.631e-08
alternative hypothesis: true mean is not equal to 100
95 percent confidence interval:
 113.7986 124.7883
sample estimates:
mean of x 
 119.2934 </code></pre>
</div>
</div>
</section>
<section id="back-to-iq-example-1" class="level2">
<h2 class="anchored" data-anchor-id="back-to-iq-example-1">Back to IQ example</h2>
<ul>
<li>Here I’ve generated a sample of 30 students with IQs on average ~ 105 points</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># One-sample t-test (greater than 100)</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(bios600, <span class="at">mu =</span> <span class="dv">100</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  bios600
t = 1.5981, df = 29, p-value = 0.1209
alternative hypothesis: true mean is not equal to 100
95 percent confidence interval:
  98.7986 109.7883
sample estimates:
mean of x 
 104.2934 </code></pre>
</div>
</div>
</section>
<section id="some-philosophical-details" class="level2">
<h2 class="anchored" data-anchor-id="some-philosophical-details">Some philosophical details</h2>
<ul>
<li><p>The obtained p-value relates to the specific test itself, so use of the same data can result in different p-values or confidence intervals depending on which test is used.</p></li>
<li><p>Importantly, we have assumed from the start that the null hypothesis is true, and the p-value calculated conditioned on that event.</p></li>
</ul>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Caution
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>p-values do NOT provide information on the probability that the null hypothesis is true given our observed data.</li>
</ul>
</div>
</div>
</section>
<section id="making-a-conclusion" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="making-a-conclusion">Making a conclusion</h2>
<ul>
<li><p>We reject the null hypothesis if the conditional probability of obtaining our test statistic, or more extreme, given it is true, is very small</p></li>
<li><p>What is “very small”? We often consider a cutpoint (the <strong>significance level</strong> or <span class="math inline">\(\alpha\)</span> level) defined prior to conducting the analysis</p></li>
<li><p>Many analyses use <span class="math inline">\(\alpha = 0.05\)</span>: if <span class="math inline">\(H_0\)</span> were in fact true, we would expect to make the wrong decision only 5% of the time (why?)</p></li>
<li><p>If the p-value is less than <span class="math inline">\(\alpha\)</span>, we say the results are <strong>statistically significant</strong> and we reject the null hypothesis. On the other hand, if the p−value is <span class="math inline">\(\alpha\)</span> or greater, we say the results are <strong>not statistically significant</strong> and fail to reject <span class="math inline">\(H_0\)</span>.</p></li>
</ul>
</section>
<section id="what-could-go-wrong" class="level2">
<h2 class="anchored" data-anchor-id="what-could-go-wrong">What could go wrong?</h2>
<ul>
<li>Suppose we test the null hypothesis <span class="math inline">\(H_0\)</span>:<span class="math inline">\(\mu = \mu_0\)</span>. We could potentially make two types of errors:</li>
</ul>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Truth</th>
<th><span class="math inline">\(\mu = \mu_0\)</span></th>
<th><span class="math inline">\(\mu \neq \mu_0\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Fail to reject <span class="math inline">\(H_0\)</span></td>
<td>correct decision</td>
<td>Type II Error</td>
</tr>
<tr class="even">
<td>Reject <span class="math inline">\(H_0\)</span></td>
<td>Type I Error</td>
<td>correct decision</td>
</tr>
</tbody>
</table>
<ul>
<li><p><strong>Type I Error</strong>: rejecting <span class="math inline">\(H_0\)</span> when it is actually true (falsely rejecting the null hypothesis)</p></li>
<li><p><strong>Type II Error</strong>: not rejecting <span class="math inline">\(H_0\)</span> when it is false (falsely failing to reject the null hypothesis)</p></li>
</ul>
</section>
<section id="type-i-vs.-type-ii-errors" class="level2">
<h2 class="anchored" data-anchor-id="type-i-vs.-type-ii-errors">Type I vs.&nbsp;Type II errors</h2>
<p><img src="images/lec-10/oraquickstick.jpg" class="img-fluid" width="100"> <img src="images/lec-10/pregnancy.jpg" class="img-fluid" alt="An image with two at-home tests. On the left is a test for HIV, which is displaying a negative result. On the right is a pregnancy test, with no result yet." width="100"></p>
</section>
<section id="type-i-vs.-type-ii-errors-1" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="type-i-vs.-type-ii-errors-1">Type I vs.&nbsp;Type II errors</h2>
<p>Example: HIV Tests</p>
<p><span class="math inline">\(H_0\)</span>: The patient does not have HIV.</p>
<ul>
<li><p>Type 1 error: Test is positive when the person does not have HIV (false positive).</p></li>
<li><p>consequence: Unnecessary stress, stigma, follow-up testing, but not life-threatening if corrected later.</p></li>
<li><p>Type II Error: test is negative when person does have HIV (false negative)</p></li>
<li><p>Consequence: very serious, patient does not get life-saving treatment, risk of transmission to others.</p></li>
<li><p>Therefore, we may design a test to minimize type II error (catch as many true cases as possible), even if that increases false positives?</p></li>
<li><p>How about pregnancy tests?</p></li>
</ul>
</section>
<section id="type-i-vs.-type-ii-errors-2" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="type-i-vs.-type-ii-errors-2">Type I vs.&nbsp;Type II errors</h2>
<p>Example: Pregnancy Tests</p>
<p><span class="math inline">\(H_0\)</span>: The person is not pregnant.</p>
<ul>
<li><p>Type I error: The pregnancy test is positive when the person is not pregnant.</p></li>
<li><p>Type II erorr: The pregnancy test is negative when the person is pregnant.</p></li>
</ul>
</section>
<section id="different-sets-of-hypotheses" class="level2">
<h2 class="anchored" data-anchor-id="different-sets-of-hypotheses">Different sets of hypotheses</h2>
<p>We set up the hypotheses to cover all possibilities for <span class="math inline">\(\mu\)</span> and consider three possibilities:</p>
<ul>
<li><p>Two-sided: <span class="math inline">\(H_0\)</span>:<span class="math inline">\(μ=μ_0\)</span>; <span class="math inline">\(H_1\)</span>:<span class="math inline">\(μ\neq μ_0\)</span></p></li>
<li><p><span class="math inline">\(H_0\)</span>:<span class="math inline">\(μ≥μ_0\)</span>; <span class="math inline">\(H_1\)</span>:<span class="math inline">\(μ&lt;μ_0\)</span></p></li>
<li><p><span class="math inline">\(H_0\)</span>:<span class="math inline">\(μ\leq μ_0\)</span>; <span class="math inline">\(H_1\)</span>:<span class="math inline">\(μ &gt; μ_0\)</span></p></li>
</ul>
</section>
<section id="different-types-of-hypotheses" class="level2">
<h2 class="anchored" data-anchor-id="different-types-of-hypotheses">Different types of hypotheses</h2>
<ul>
<li><p>Let’s go back to the IQ example</p></li>
<li><p>Are BIOS 600 students smarter than average?</p>
<ul>
<li><span class="math inline">\(H_0\)</span> = The average IQ of BIOS 600 students is equal to 100 points.</li>
<li><span class="math inline">\(H_A\)</span> = The average IQ of BIOS 600 students is greater than 100 points.</li>
</ul></li>
<li><p>Are BIOS 600 students IQs different than the average?</p>
<ul>
<li><span class="math inline">\(H_0\)</span> = The average IQ of BIOS 600 students is equal to 100 points.</li>
<li><span class="math inline">\(H_A\)</span> = The average IQ of BIOS 600 students is not equal to 100 points.</li>
</ul></li>
</ul>
</section>
<section id="why-not-use-a-one-sided-test" class="level2">
<h2 class="anchored" data-anchor-id="why-not-use-a-one-sided-test">Why not use a one-sided test?</h2>
<p><img src="images/lec-10/nejm.png" class="img-fluid" alt="An article from the New England Journal of Medicine from March 21, 1991 with title Mortality and Morbidity in Patients Receiving Encainide, Flecainide, or Placebo: The Cardiac Arrhythmia Suppression Trial" width="400"></p>
</section>
<section id="why-not-use-a-one-sided-test-1" class="level2">
<h2 class="anchored" data-anchor-id="why-not-use-a-one-sided-test-1">Why not use a one-sided test?</h2>
<ul>
<li><p>In this study, researchers tested whether anti-arrhythmic drugs (like encainide and flecainide) reduced mortality and morbidity among patients with arrhythmias following a heart attack.</p></li>
<li><p>While the initial hypothesis may have been that these drugs would help reduce mortality (a one-sided hypothesis), the study actually found the opposite: the drugs increased mortality rates significantly, leading to the early termination of the trial.</p></li>
</ul>
</section>
<section id="why-a-two-sided-test-is-important" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="why-a-two-sided-test-is-important">Why a two-sided test is important</h2>
<ul>
<li><p>Unexpected Adverse Effects: In biomedical research, especially in clinical trials, it’s crucial to remain open to the possibility of unexpected results. If the researchers had used a one-sided test, assuming only that the drugs could be beneficial, they might have missed the possibility that the drugs could cause harm. A two-sided test accounts for both the potential benefit and harm, ensuring a more balanced and rigorous assessment of treatment effects.</p></li>
<li><p>Ethical considerations: Since the primary concern in clinical trials is patient safety, it’s critical to detect any harmful effects early. A one-sided hypothesis test only tests for improvement, which could delay recognizing adverse outcomes—potentially leading to increased patient harm, as seen in the CAST trial.</p></li>
</ul>
</section>
<section id="recap" class="level2">
<h2 class="anchored" data-anchor-id="recap">Recap</h2>
<ul>
<li><p>Using a t-distribution vs.&nbsp;a z-distribution to create confidence intervals</p></li>
<li><p><code>qt()</code> function</p></li>
<li><p>Hypothesis tests: how to conduct them, how to interpret them</p></li>
<li><p>Type 1 and Type 2 error</p></li>
<li><p>Why a two-sided test (vs.&nbsp;one-sided) is important</p></li>
</ul>
</section>
<section id="next-class" class="level2">
<h2 class="anchored" data-anchor-id="next-class">Next Class</h2>
<ul>
<li>Comparing two means</li>
</ul>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>