<!DOCTYPE html>
<html lang="en"><head>
<script src="lec-10-hypothesis_AGH_files/libs/clipboard/clipboard.min.js"></script>
<script src="lec-10-hypothesis_AGH_files/libs/quarto-html/tabby.min.js"></script>
<script src="lec-10-hypothesis_AGH_files/libs/quarto-html/popper.min.js"></script>
<script src="lec-10-hypothesis_AGH_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="lec-10-hypothesis_AGH_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="lec-10-hypothesis_AGH_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="lec-10-hypothesis_AGH_files/libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.26">

  <title>Lecture 10: Hypothesis Testing</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="lec-10-hypothesis_AGH_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="lec-10-hypothesis_AGH_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="lec-10-hypothesis_AGH_files/libs/revealjs/dist/theme/quarto-534cd8e3a96973385dffff3f4709048d.css">
  <link rel="stylesheet" href="reveal-custom.css">
  <link href="lec-10-hypothesis_AGH_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="lec-10-hypothesis_AGH_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="lec-10-hypothesis_AGH_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="lec-10-hypothesis_AGH_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Lecture 10: Hypothesis Testing</h1>
  <p class="subtitle">BIOS 600 - Spring 2026</p>

<div class="quarto-title-authors">
</div>

</section>
<section id="announcements" class="slide level2">
<h2>Announcements</h2>
<ul>
<li><p>Exam scores are posted on Canvas.</p></li>
<li><p>Feel free to reach out to me if you’d like to schedule an appointment to discuss your exam.</p></li>
<li><p>There will be an opportunity to earn back up to half of the points you missed by reworking those problems</p></li>
<li><p>More specific details to come soon</p></li>
</ul>
</section>
<section id="announcements-1" class="slide level2">
<h2>Announcements</h2>
<ul>
<li><p>HW 4 due <strong>Thursday at 11:59pm</strong></p></li>
<li><p>Lab 5 has been posted and due <strong>Friday at 11:59pm</strong></p></li>
</ul>
</section>
<section id="overview" class="slide level2">
<h2>Overview</h2>
<ul>
<li><p><code>qt()</code> function</p></li>
<li><p>Hypothesis tests: how to conduct them, how to interpret them</p></li>
</ul>
</section>
<section id="review-from-last-week" class="slide level2">
<h2>Review from last week</h2>
<ul>
<li>When constructing a confidence interval with known <span class="math inline">\(\sigma\)</span> we need <span class="math inline">\(Z \sim N(0,1)\)</span></li>
</ul>
<p><span class="math display">\[\textrm{Point estimate} \pm \underbrace{\textrm{confidence multiplier} \times \textrm{standard error}}_{\text{Margin of error}}\]</span></p>
<p><span class="math display">\[(\bar X - z^*_{1-\alpha/2} \frac{\sigma}{\sqrt n}, \bar X + z^*_{1-\alpha/2} \frac{\sigma}{\sqrt n})\]</span></p>
</section>
<section id="review-from-last-week-1" class="slide level2">
<h2>Review from last week</h2>
<ul>
<li>When constructing a confidence interval with <strong>unknown</strong> <span class="math inline">\(\sigma\)</span>, we need the <strong><span class="math inline">\(t^*\)</span> critical value</strong>.</li>
</ul>
<p><span class="math display">\[(\bar X - t^*_{n-1; 1-\alpha/2} \frac{s}{\sqrt n}, \bar X + t^*_{n-1; 1-\alpha/2} \frac{s}{\sqrt n})\]</span></p>
</section>
<section id="helpful-code-for-hw-4" class="slide level2">
<h2>Helpful code for HW 4</h2>
<ul>
<li><p>For the <strong><span class="math inline">\(t^*\)</span> distribution</strong></p></li>
<li><p>R provides two functions:</p>
<ul>
<li><code>pt()</code> → cumulative probability (area to the left)</li>
<li><code>qt()</code> → quantile function (finds cutoff given probability)</li>
</ul></li>
</ul>
</section>
<section id="example-code" class="slide level2">
<h2>Example code</h2>
<p>Suppose we want a 95% confidence interval with <span class="math inline">\(n = 20\)</span> observations:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href=""></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb1-2"><a href=""></a>n <span class="ot">&lt;-</span> <span class="dv">20</span></span>
<span id="cb1-3"><a href=""></a></span>
<span id="cb1-4"><a href=""></a><span class="co"># degrees of freedom</span></span>
<span id="cb1-5"><a href=""></a>df <span class="ot">&lt;-</span> n <span class="sc">-</span> <span class="dv">1</span>  </span>
<span id="cb1-6"><a href=""></a></span>
<span id="cb1-7"><a href=""></a><span class="co"># t critical value</span></span>
<span id="cb1-8"><a href=""></a>t_crit <span class="ot">&lt;-</span> <span class="fu">qt</span>(<span class="dv">1</span> <span class="sc">-</span> alpha<span class="sc">/</span><span class="dv">2</span>, <span class="at">df =</span> df)</span>
<span id="cb1-9"><a href=""></a>t_crit</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.093024</code></pre>
</div>
</div>
<ul>
<li>This is the cutoff value such that 95% of the <span class="math inline">\(t_{19}\)</span> distribution lies between <span class="math inline">\(-t\)</span> and <span class="math inline">\(+t\)</span>.</li>
</ul>
</section>
<section id="t-critical-values" class="slide level2 smaller">
<h2><span class="math inline">\(t\)</span> critical values</h2>

<img data-src="lec-10-hypothesis_AGH_files/figure-revealjs/unnamed-chunk-2-1.png" width="960" class="r-stretch"></section>
<section id="reading" class="slide level2">
<h2>Reading</h2>
<ul>
<li><p>P &amp; G: 10.1 - 10.4</p></li>
<li><p>OI: 5.3</p></li>
</ul>
</section>
<section id="remember-iq-example" class="slide level2">
<h2>Remember IQ example?</h2>
<ul>
<li><p>IQ tests have a distribution with <span class="math inline">\(\mu\)</span> = 100 and <strong>known</strong> <span class="math inline">\(\sigma\)</span> = 15</p></li>
<li><p>For a random sample of <span class="math inline">\(n = 30\)</span>, BIOS 600 students, the sample average IQ score is 120</p></li>
<li><p>The central limit theorem tells us that the distribution of means of samples of size 30 from this population is also normal, with mean <span class="math inline">\(\mu = 100\)</span> and <span class="math inline">\(SE = \sigma/ \sqrt{n} = 15 \sqrt{30} \approx 2.7\)</span></p></li>
</ul>
</section>
<section id="remember-iq-example-1" class="slide level2 smaller">
<h2>Remember IQ example?</h2>
<ul>
<li>Remember here I <strong>know</strong> <span class="math inline">\(\sigma\)</span>, I can derive 95% confidence interval for the BIOS 600 students average IQ</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href=""></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb3-2"><a href=""></a><span class="fu">qnorm</span>(<span class="dv">1</span><span class="sc">-</span>(alpha<span class="sc">/</span><span class="dv">2</span>), <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.959964</code></pre>
</div>
</div>
<p><span class="math display">\[(120 - 1.96 *\frac{15}{\sqrt 30}, 120 + 1.96 * \frac{15}{\sqrt 30}) = (114.6, 125.4)\]</span></p>
<ul>
<li>I am 95% confident the true mean IQ for Bios 600 students falls between 114.6 and 125.4</li>
</ul>
</section>
<section id="lets-say-i-dont-know-sigma" class="slide level2">
<h2>Let’s say I don’t know sigma</h2>
<ul>
<li>Let’s say for a random sample of <span class="math inline">\(n = 30\)</span>, BIOS 600 students, the sample average IQ score is 120 with <strong>sample</strong> standard deviation of 15. I can still derive 95% confidence interval for the BIOS 600 students average IQ using the t-distribution</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href=""></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb5-2"><a href=""></a>n <span class="ot">&lt;-</span> <span class="dv">30</span></span>
<span id="cb5-3"><a href=""></a></span>
<span id="cb5-4"><a href=""></a><span class="co"># degrees of freedom</span></span>
<span id="cb5-5"><a href=""></a>df <span class="ot">&lt;-</span> n <span class="sc">-</span> <span class="dv">1</span>  </span>
<span id="cb5-6"><a href=""></a></span>
<span id="cb5-7"><a href=""></a><span class="co"># t critical value</span></span>
<span id="cb5-8"><a href=""></a>t_crit <span class="ot">&lt;-</span> <span class="fu">qt</span>(<span class="dv">1</span> <span class="sc">-</span> alpha<span class="sc">/</span><span class="dv">2</span>, <span class="at">df =</span> df)</span>
<span id="cb5-9"><a href=""></a>t_crit</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.04523</code></pre>
</div>
</div>
</section>
<section id="remember-iq-example-2" class="slide level2">
<h2>Remember IQ example?</h2>
<ul>
<li>I have 95% confidence that the true mean IQ for BIOS 600 students is between 114.4 and 125.6</li>
</ul>
<p><span class="math display">\[(120 - 2.045 *\frac{15}{\sqrt 30}, 120 + 2.045 * \frac{15}{\sqrt 30}) = (114.4, 125.6)\]</span></p>
</section>
<section id="remember-iq-example-3" class="slide level2">
<h2>Remember IQ example?</h2>
<ul>
<li><p>Let’s go back to knowing <span class="math inline">\(\sigma\)</span>, what if I want to test whether BIOS 600 students are smarter than average?</p></li>
<li><p><span class="math inline">\(Z = \frac{\bar{X} - \mu}{SE}\)</span> is a standard normal random variable</p></li>
<li><p><span class="math inline">\(Z \approx 7.3\)</span></p></li>
</ul>
</section>
<section id="how-can-we-answer-research-questions-using-statistics" class="slide level2">
<h2>How can we answer research questions using statistics?</h2>
<ul>
<li><strong>Statistical hypothesis testing</strong> is the procedure that assesses evidence provided by the data in favor of or against some claim about the population (often about a population parameter or potential associations).</li>
</ul>
</section>
<section id="the-hypothesis-testing-framework" class="slide level2">
<h2>The hypothesis testing framework</h2>
<ol type="1">
<li><p>Start with two hypotheses about the population: the <strong>null hypothesis</strong> and the <strong>alternative hypothesis</strong></p></li>
<li><p>Choose a sample, collect data, and analyze the data</p></li>
<li><p>Figure out how likely it is to see data like what we got/observed, IF the null hypothesis were true</p></li>
<li><p>If our data would have been extremely unlikely if the null claim were true, then we reject it and deem the alternative claim worthy of further study. Otherwise, we <strong>cannot reject the null</strong> claim</p></li>
</ol>
</section>
<section id="example-ultra-low-dose-contraception" class="slide level2 smaller">
<h2>Example: Ultra-low dose contraception</h2>
<ul>
<li><p>Oral contraceptive pills work well, but must have a precise dose of estrogen.</p></li>
<li><p>If a pill has too high a dose, then people may risk side effects such as headaches, nausea, and rare but potentially fatal blood clots</p></li>
<li><p>If a pill has too low a dose, pregnancy may occur</p></li>
</ul>
</section>
<section id="ultra-low-dose-contraception" class="slide level2">
<h2>Ultra-low dose contraception</h2>
<ul>
<li><p>A certain contraceptive pill is supposed to contain precisely 0.020 <span class="math inline">\(\mu g\)</span> of estrogen.</p></li>
<li><p>During quality control, 50 randomly selected pills are tested, with a sample mean dose 0.017 <span class="math inline">\(\mu g\)</span> and <strong>sample SD</strong> 0.0008 <span class="math inline">\(\mu g\)</span>.</p></li>
</ul>
<div class="callout callout-caution callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Question</strong></p>
</div>
<div class="callout-content">
<p>Do you think this is cause for concern? Why or why not?</p>
</div>
</div>
</div>
</section>
<section id="two-competing-hypotheses" class="slide level2">
<h2>Two competing hypotheses</h2>
<ul>
<li><p>The <strong>null hypothesis</strong> (<span class="math inline">\(H_0\)</span>) states that “nothing unusual is happening” / there is no change from status quo / there is no relationship / etc.</p></li>
<li><p>The <strong>alternative hypothesis</strong> (<span class="math inline">\(H_A\)</span> or <span class="math inline">\(H_1\)</span>) states the opposite: that there is some sort of relationship (usually this is what we want to check or really think is happening)</p></li>
</ul>
<p>Remember, in statistical hypothesis testing we <em>always first assume the null hypothesis is true</em>, and see whether we reject or fail to reject this claim.</p>
</section>
<section id="defining-the-null-and-alternative-hypotheses" class="slide level2 smaller">
<h2>Defining the null and alternative hypotheses</h2>
<p>Stated in words:</p>
<ul>
<li><p><span class="math inline">\(H_0\)</span>: The pills are consistent with a population that has a mean of 0.020 <span class="math inline">\(\mu\)</span>g estrogen</p></li>
<li><p><span class="math inline">\(H_1\)</span>: The pills are not consistent with a population that has a mean of 0.020 <span class="math inline">\(\mu\)</span>g estrogen</p></li>
</ul>
<p>Stated in symbols (using LaTeX):</p>
<p><code>$H_0$: $\mu = 0.020$</code> renders to —&gt; <span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu\)</span> = 0.020</p>
<p><code>$H_1$: $\mu \neq 0.020$</code> renders to —&gt; <span class="math inline">\(H_1\)</span>: <span class="math inline">\(\mu \neq\)</span> 0.020</p>
<p>where <span class="math inline">\(\mu\)</span> is the mean estrogen level of the manufactured pills, in <span class="math inline">\(\mu\)</span>g.</p>
</section>
<section id="collecting-and-summarizing-the-data" class="slide level2">
<h2>Collecting and summarizing the data</h2>
<p>With these two hypotheses, we now take a sample and summarize the data</p>
<ul>
<li><p>The choice of <strong>summary statistic</strong> calculated depends on the type of data as well as its distribution.</p></li>
<li><p>In our example, quality control technicians randomly selected a sample of 50 pills and calculated the sample mean <span class="math inline">\(\bar{x}\)</span> = 0.017 <span class="math inline">\(\mu\)</span>g and <strong>sample standard deviation</strong> <span class="math inline">\(s\)</span> = 0.008 <span class="math inline">\(\mu\)</span>g.</p></li>
</ul>
</section>
<section id="collecting-the-data-in-r" class="slide level2">
<h2>Collecting the data in R</h2>
<ul>
<li>(For purposes of this example, we’ve simulated the data with the desired sample size, mean, and sd)</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href=""></a>df <span class="sc">|&gt;</span></span>
<span id="cb7-2"><a href=""></a>  <span class="fu">slice</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  sample_data
1  0.01251619
2  0.01515858
3  0.02946967
4  0.01756407
5  0.01803430</code></pre>
</div>
</div>
</section>
<section id="assessing-the-evidence-observed" class="slide level2">
<h2>Assessing the evidence observed</h2>
<ul>
<li><p>Next, we calculate the probability of getting data like ours, or more extreme, if <span class="math inline">\(H_0\)</span> were actually true.</p></li>
<li><p>This is a conditional probability: “if <span class="math inline">\(H_0\)</span> were true (i.e., if <span class="math inline">\(\mu\)</span> were truly 0.020), what would be the probability of observing <span class="math inline">\(\bar{x}\)</span> = 0.017 and <span class="math inline">\(s\)</span> = 0.008?</p></li>
<li><p>This probability is the <strong>p-value</strong>.</p></li>
<li><p>P(observing <span class="math inline">\(\bar{x}\)</span> = 0.017 and <span class="math inline">\(s\)</span> = 0.008 | <span class="math inline">\(H_0\)</span> were true)</p></li>
</ul>
</section>
<section id="perform-one-sample-t-test-against-mu-0.020" class="slide level2">
<h2>Perform one-sample t-test against mu = 0.020</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href=""></a><span class="fu">t.test</span>(df<span class="sc">$</span>sample_data, <span class="at">mu =</span> <span class="fl">0.020</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  df$sample_data
t = -2.6012, df = 49, p-value = 0.01225
alternative hypothesis: true mean is not equal to 0.02
95 percent confidence interval:
 0.01517019 0.01938026
sample estimates:
 mean of x 
0.01727523 </code></pre>
</div>
</div>
<ul>
<li>Where does -2.6012 come from?</li>
</ul>
</section>
<section id="two-sided-tests-of-hypotheses" class="slide level2 smaller">
<h2>Two-sided tests of hypotheses</h2>
<ul>
<li>To conduct the hypothesis test, we use what we learned about the sampling distribution of the sample mean <span class="math inline">\(\bar{X}\)</span>. If the underlying population is normally distributed (or <span class="math inline">\(n\)</span> is pretty large), then the random variable</li>
</ul>
<div class="poll">
<p><span class="math display">\[t = \frac{\bar{X}-\mu_0}{s/\sqrt{n}}\]</span></p>
</div>
<p>has a <span class="math inline">\(t_{n-1}\)</span> distribution.</p>
</section>
<section id="breaking-down-the-test-statistic" class="slide level2">
<h2>Breaking down the test statistic</h2>
<div class="poll">
<p><span class="math display">\[t = \frac{\bar{X}-\mu_0}{s/\sqrt{n}}\]</span></p>
</div>
<ul>
<li><span class="math inline">\(\bar{X} - \mu_0\)</span> tells us how far our sample mean is from the hypothesized population mean</li>
</ul>
<p>Thus, the test statistic <span class="math inline">\(t\)</span> is an estimate of how many SDs apart <span class="math inline">\(\mu_0\)</span> and <span class="math inline">\(\bar{X}\)</span> are from each other</p>
<ul>
<li>Let’s calculate our test statistic using the above formula:</li>
</ul>
</section>
<section id="breaking-down-the-test-statistic-1" class="slide level2">
<h2>Breaking down the test statistic</h2>
</section>
<section id="example-conclusion" class="slide level2 smaller">
<h2>Example: Conclusion</h2>
<ul>
<li><p>If the true average estrogen level really were 0.020 <span class="math inline">\(\mu\)</span>g, the chance of seeing data this far off just by random luck is about 1 in 100. (P-value = .01225)</p></li>
<li><p>Since that’s very unlikely, we have good evidence the pills’ average estrogen level is not actually 0.020 <span class="math inline">\(\mu\)</span>g.</p></li>
<li><p><strong>Conclusion</strong>: At an alpha level of 0.05, we calculated a p-value of 0.012, which is less than 0.05. There is statistically significant evidence that the mean estrogen level of the manufactured pills is different than 0.020 <span class="math inline">\(\mu\)</span>g.</p></li>
<li><p>In other words: the pills are probably being made with a slightly different average amount of estrogen than intended.</p></li>
</ul>
</section>
<section id="getting-the-p-value-graphically-drawing" class="slide level2">
<h2>Getting the p-value graphically (drawing)</h2>
</section>
<section id="breaking-down-the-test-statistic-2" class="slide level2">
<h2>Breaking down the test statistic</h2>
<ul>
<li><p>The <strong>pt</strong> function is similar to <strong>pnorm</strong></p></li>
<li><p>Probability our observation is the left of 2.6012 is:</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href=""></a><span class="fu">pt</span>(<span class="fl">2.6012</span>, <span class="at">df=</span><span class="dv">49</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9938754</code></pre>
</div>
</div>
<ul>
<li>Probability we observe something as high as 2.6012 or something more extreme</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href=""></a>p_high <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">-</span><span class="fu">pt</span>(<span class="fl">2.6012</span>, <span class="at">df=</span><span class="dv">49</span>)</span>
<span id="cb13-2"><a href=""></a>p_high</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.006124635</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href=""></a><span class="dv">2</span><span class="sc">*</span>p_high</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.01224927</code></pre>
</div>
</div>
</section>
<section id="reflection" class="slide level2">
<h2>Reflection</h2>

<img data-src="images/lec-10/p-hack_1.png" class="r-stretch"></section>
<section id="reflection-1" class="slide level2">
<h2>Reflection</h2>

<img data-src="images/lec-10/p-hack_2.png" class="r-stretch"></section>
<section id="reflection-2" class="slide level2">
<h2>Reflection</h2>

<img data-src="images/lec-10/p-hack_3.png" class="r-stretch"></section>
<section id="but-wait" class="slide level2">
<h2>But wait…</h2>
<ul>
<li><p>What if <span class="math inline">\(p \geq \alpha\)</span>?</p></li>
<li><p>We <strong>never</strong> “accept” the null hypothesis – we assumed that <span class="math inline">\(H_0\)</span> was true to begin with and assessed the probability of obtaining our test statistic (or more extreme) under this assumption</p></li>
<li><p>When we fail to reject the null hypothesis, we are stating that there is <em>insufficient evidence</em> to assert that it is false</p></li>
</ul>
</section>
<section id="back-to-iq-example" class="slide level2">
<h2>Back to IQ example</h2>
<ul>
<li><p>Here a sample of 30 students with IQs on average of 120 points. Can we test if the average IQ score for BIOS 600 students is the same as that in the larger population?</p></li>
<li><p><span class="math inline">\(H_0\)</span> =</p></li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  bios600
t = 7.1812, df = 29, p-value = 6.631e-08
alternative hypothesis: true mean is not equal to 100
95 percent confidence interval:
 113.7986 124.7883
sample estimates:
mean of x 
 119.2934 </code></pre>
</div>
</div>
</section>
<section id="back-to-iq-example-1" class="slide level2">
<h2>Back to IQ example</h2>
<ul>
<li>Here I’ve generated a sample of 30 students with IQs on average ~ 105 points</li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  bios600
t = 1.5981, df = 29, p-value = 0.1209
alternative hypothesis: true mean is not equal to 100
95 percent confidence interval:
  98.7986 109.7883
sample estimates:
mean of x 
 104.2934 </code></pre>
</div>
</div>
</section>
<section id="some-philosophical-details" class="slide level2">
<h2>Some philosophical details</h2>
<ul>
<li><p>The obtained p-value relates to the specific test itself, so use of the same data can result in different p-values or confidence intervals depending on which test is used.</p></li>
<li><p>Importantly, we have assumed from the start that the null hypothesis is true, and the p-value calculated conditioned on that event.</p></li>
</ul>
<div class="callout callout-caution callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Caution</strong></p>
</div>
<div class="callout-content">
<ul>
<li>p-values do NOT provide information on the probability that the null hypothesis is true given our observed data.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="making-a-conclusion" class="slide level2 smaller">
<h2>Making a conclusion</h2>
<ul>
<li><p>We reject the null hypothesis if the conditional probability of obtaining our test statistic, or more extreme, given it is true, is very small</p></li>
<li><p>What is “very small”? We often consider a cutpoint (the <strong>significance level</strong> or <span class="math inline">\(\alpha\)</span> level) defined prior to conducting the analysis</p></li>
<li><p>Many analyses use <span class="math inline">\(\alpha = 0.05\)</span>: if <span class="math inline">\(H_0\)</span> were in fact true, we would expect to make the wrong decision only 5% of the time (why?)</p></li>
<li><p>If the p-value is less than <span class="math inline">\(\alpha\)</span>, we say the results are <strong>statistically significant</strong> and we reject the null hypothesis. On the other hand, if the p−value is <span class="math inline">\(\alpha\)</span> or greater, we say the results are <strong>not statistically significant</strong> and fail to reject <span class="math inline">\(H_0\)</span>.</p></li>
</ul>
</section>
<section id="what-could-go-wrong" class="slide level2">
<h2>What could go wrong?</h2>
<ul>
<li>Suppose we test the null hypothesis <span class="math inline">\(H_0\)</span>:<span class="math inline">\(\mu = \mu_0\)</span>. We could potentially make two types of errors:</li>
</ul>
<table class="caption-top">
<thead>
<tr class="header">
<th>Truth</th>
<th><span class="math inline">\(\mu = \mu_0\)</span></th>
<th><span class="math inline">\(\mu \neq \mu_0\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Fail to reject <span class="math inline">\(H_0\)</span></td>
<td>correct decision</td>
<td>Type II Error</td>
</tr>
<tr class="even">
<td>Reject <span class="math inline">\(H_0\)</span></td>
<td>Type I Error</td>
<td>correct decision</td>
</tr>
</tbody>
</table>
<ul>
<li><p><strong>Type I Error</strong>: rejecting <span class="math inline">\(H_0\)</span> when it is actually true (falsely rejecting the null hypothesis)</p></li>
<li><p><strong>Type II Error</strong>: not rejecting <span class="math inline">\(H_0\)</span> when it is false (falsely failing to reject the null hypothesis)</p></li>
</ul>
</section>
<section id="type-i-vs.-type-ii-errors" class="slide level2">
<h2>Type I vs.&nbsp;Type II errors</h2>
<p><img data-src="images/lec-10/oraquickstick.jpg" width="100"> <img data-src="images/lec-10/pregnancy.jpg" width="100"></p>
</section>
<section id="type-i-vs.-type-ii-errors-1" class="slide level2 smaller">
<h2>Type I vs.&nbsp;Type II errors</h2>
<p>Example: HIV Tests</p>
<p><span class="math inline">\(H_0\)</span>: The patient does not have HIV.</p>
<ul>
<li><p>Type 1 error: Test is positive when the person does not have HIV (false positive).</p></li>
<li><p>consequence: Unnecessary stress, stigma, follow-up testing, but not life-threatening if corrected later.</p></li>
<li><p>Type II Error: test is negative when person does have HIV (false negative)</p></li>
<li><p>Consequence: very serious, patient does not get life-saving treatment, risk of transmission to others.</p></li>
<li><p>Therefore, we may design a test to minimize type II error (catch as many true cases as possible), even if that increases false positives?</p></li>
<li><p>How about pregnancy tests?</p></li>
</ul>
</section>
<section id="type-i-vs.-type-ii-errors-2" class="slide level2 smaller">
<h2>Type I vs.&nbsp;Type II errors</h2>
<p>Example: Pregnancy Tests</p>
<p><span class="math inline">\(H_0\)</span>:</p>
<ul>
<li><p>Type I error:</p></li>
<li><p>Type II erorr:</p></li>
</ul>
</section>
<section id="different-sets-of-hypotheses" class="slide level2">
<h2>Different sets of hypotheses</h2>
<p>We set up the hypotheses to cover all possibilities for <span class="math inline">\(\mu\)</span> and consider three possibilities:</p>
<ul>
<li><p>Two-sided: <span class="math inline">\(H_0\)</span>:<span class="math inline">\(μ=μ_0\)</span>; <span class="math inline">\(H_1\)</span>:<span class="math inline">\(μ\neq μ_0\)</span></p></li>
<li><p><span class="math inline">\(H_0\)</span>:<span class="math inline">\(μ≥μ_0\)</span>; <span class="math inline">\(H_1\)</span>:<span class="math inline">\(μ&lt;μ_0\)</span></p></li>
<li><p><span class="math inline">\(H_0\)</span>:<span class="math inline">\(μ\leq μ_0\)</span>; <span class="math inline">\(H_1\)</span>:<span class="math inline">\(μ &gt; μ_0\)</span></p></li>
</ul>
</section>
<section id="different-types-of-hypotheses" class="slide level2">
<h2>Different types of hypotheses</h2>
<ul>
<li><p>Let’s go back to the IQ example</p></li>
<li><p>Are BIOS 600 students smarter than average?</p>
<ul>
<li><span class="math inline">\(H_0\)</span> =</li>
<li><span class="math inline">\(H_A\)</span> =</li>
</ul></li>
<li><p>Are BIOS 600 students IQs different than the average?</p>
<ul>
<li><span class="math inline">\(H_0\)</span> =</li>
<li><span class="math inline">\(H_A\)</span> =</li>
</ul></li>
</ul>
</section>
<section id="why-not-use-a-one-sided-test" class="slide level2">
<h2>Why not use a one-sided test?</h2>

<img data-src="images/lec-10/nejm.png" width="400" class="r-stretch"></section>
<section id="why-not-use-a-one-sided-test-1" class="slide level2">
<h2>Why not use a one-sided test?</h2>
<ul>
<li><p>In this study, researchers tested whether anti-arrhythmic drugs (like encainide and flecainide) reduced mortality and morbidity among patients with arrhythmias following a heart attack.</p></li>
<li><p>While the initial hypothesis may have been that these drugs would help reduce mortality (a one-sided hypothesis), the study actually found the opposite: the drugs increased mortality rates significantly, leading to the early termination of the trial.</p></li>
</ul>
</section>
<section id="why-a-two-sided-test-is-important" class="slide level2 smaller">
<h2>Why a two-sided test is important</h2>
<ul>
<li><p>Unexpected Adverse Effects: In biomedical research, especially in clinical trials, it’s crucial to remain open to the possibility of unexpected results. If the researchers had used a one-sided test, assuming only that the drugs could be beneficial, they might have missed the possibility that the drugs could cause harm. A two-sided test accounts for both the potential benefit and harm, ensuring a more balanced and rigorous assessment of treatment effects.</p></li>
<li><p>Ethical considerations: Since the primary concern in clinical trials is patient safety, it’s critical to detect any harmful effects early. A one-sided hypothesis test only tests for improvement, which could delay recognizing adverse outcomes—potentially leading to increased patient harm, as seen in the CAST trial.</p></li>
</ul>
</section>
<section id="recap" class="slide level2">
<h2>Recap</h2>
<ul>
<li><p><code>qt()</code> function</p></li>
<li><p>Hypothesis tests: how to conduct them, how to interpret them</p></li>
<li><p>Type 1 and Type 2 error</p></li>
<li><p>Why a two-sided test (vs.&nbsp;one-sided) is important</p></li>
</ul>
</section>
<section id="next-class" class="slide level2">
<h2>Next class</h2>
<ul>
<li>Comparing two means</li>
</ul>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="images/logo_600.png" class="slide-logo"></p>
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="lec-10-hypothesis_AGH_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="lec-10-hypothesis_AGH_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="lec-10-hypothesis_AGH_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="lec-10-hypothesis_AGH_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="lec-10-hypothesis_AGH_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="lec-10-hypothesis_AGH_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="lec-10-hypothesis_AGH_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="lec-10-hypothesis_AGH_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="lec-10-hypothesis_AGH_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="lec-10-hypothesis_AGH_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: false,

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    

    <script>

      // htmlwidgets need to know to resize themselves when slides are shown/hidden.

      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current

      // slide changes (different for each slide format).

      (function () {

        // dispatch for htmlwidgets

        function fireSlideEnter() {

          const event = window.document.createEvent("Event");

          event.initEvent("slideenter", true, true);

          window.document.dispatchEvent(event);

        }

    

        function fireSlideChanged(previousSlide, currentSlide) {

          fireSlideEnter();

    

          // dispatch for shiny

          if (window.jQuery) {

            if (previousSlide) {

              window.jQuery(previousSlide).trigger("hidden");

            }

            if (currentSlide) {

              window.jQuery(currentSlide).trigger("shown");

            }

          }

        }

    

        // hookup for slidy

        if (window.w3c_slidy) {

          window.w3c_slidy.add_observer(function (slide_num) {

            // slide_num starts at position 1

            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);

          });

        }

    

      })();

    </script>

    

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>