---
title: "Final Exam Info"
format: html
---

- Exam 02 will take place in-person on Tuesday, May 5 from 8:00 AM to 11:00 AM. This exam is an opportunity to demonstrate what you've learned in the course, primarily on content **since the last exam** (but not completely excluding material you learned previously - it's difficult to completely separate out certain topics as they build on each other).  

- If your last name starts with A-K you will be in McGavran-Greenberg Hall 2301, if your last name starts with L-Z you will be in this classroom (same rooms as last exam)

- The exam will be closed-book. 

- You should bring something to write with. Nothing else is permitted (i.e. calculators not permitted, cheat sheets not permitted.)

- Content covered: Lectures 16-21, Labs 7-8, AE 5-6. 

## Types of questions

- The questions may be mostly short answer and one set of true/false questions - although maybe one or two multiple choice

- To prepare, review the definitions, concepts, and examples in the lectures. Review all lab assignments, homework assignments, and AEs listed above. With each question, ask yourself "Why?" Why does this matter? Why might this concept be helpful when doing biostatistics in the real world? Can I explain this question to someone else who does not have statistics experience?

- Code, Applied and Conceptual will be mixed in across all questions 

## Resources for reviewing

- No formula sheet will be provided; all questions can be answered without one.

- A topics list is available as `final-topics`.

- I will prepare a set of review questions for us to complete in class on Thursday April 23. We will go over these together and you will have access to the solutions after class. 

- I will post additional problems to work this week for you to try on your own
